Nama: Nadya Angelie Lislie

NIM: [removed]

In [ ]:
#pip install gensim

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import re
import nltk
from nltk.tokenize import word_tokenize
import warnings
warnings.filterwarnings('ignore')

In [ ]:
#mount drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df=pd.read_csv('/content/drive/My Drive/Colab Notebooks/Emotion_classify_Data.csv')

In [ ]:
df.head()

                                             Comment Emotion
0  i seriously hate one subject to death but now ...    fear
1                 im so full of life i feel appalled   anger
2  i sit here to write i start to dig out my feel...    fear
3  ive been really angry with r and i feel like a...     joy
4  i feel suspicious if there is no one outside l...    fear

In [ ]:
df.shape

(5937, 2)

In [ ]:
df['Emotion'].value_counts()

Emotion
anger    2000
joy      2000
fear     1937
Name: count, dtype: int64

In [ ]:
#Encoding Categorical to Numeric of Gender and Ever_Married
label_encode={"Emotion": {"anger":0,"joy" :1,"fear":2}}
df=df.replace(label_encode)

In [ ]:
df.head()

                                             Comment  Emotion
0  i seriously hate one subject to death but now ...        2
1                 im so full of life i feel appalled        0
2  i sit here to write i start to dig out my feel...        2
3  ive been really angry with r and i feel like a...        1
4  i feel suspicious if there is no one outside l...        2

In [ ]:
def cleansing(df):
    df_clean=df.str.lower()
    df_clean=[re.sub(r"\d+","",i )for i in df_clean]
    df_clean=[re.sub(r'[^\w]', ' ', i)for i in df_clean]
    df_clean=[re.sub(r'\s+',' ',i)for i in df_clean]
    return df_clean

In [ ]:
df['clean_text']=cleansing(df['Comment'])

In [ ]:
df.head()

,Comment,Emotion,clean_text
0,i seriously hate one subject to death but now ...,2,i seriously hate one subject to death but now ...
1,im so full of life i feel appalled,0,im so full of life i feel appalled
2,i sit here to write i start to dig out my feel...,2,i sit here to write i start to dig out my feel...
3,ive been really angry with r and i feel like a...,1,ive been really angry with r and i feel like a...
4,i feel suspicious if there is no one outside l...,2,i feel suspicious if there is no one outside l...

In [ ]:
#check maximum length of word in sentence
max_sen = df['clean_text'].str.split().str.len().max()

In [ ]:
max_sen

64

**Split the Data**

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, roc_auc_score, log_loss
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df['clean_text'], df['Emotion'], test_size = 0.2, random_state = 42,stratify=df['Emotion'])

In [ ]:
len(x_train)

4749

In [ ]:
x_train.head()

75      i fear that other people ask me about my feeli...
2605    ive been thinking about what it is that drives...
4619                         i love comments so feel free
1835    i feel irritable like no other and running wil...
2832    i dont have a yeast infection in the vagina i ...
Name: clean_text, dtype: object

In [ ]:
 max_sen=x_train.str.split().str.len().max()

**Remove Stopword and Tokenization**

In [ ]:
#Define Stopwords
from nltk.corpus import stopwords
nltk.download('stopwords')
# Get a list of stop words in the English language
stop_words = set(stopwords.words('english'))

# Display the top 20 stop words
list(stop_words)[:20]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

['i',
 'an',
 'while',
 'she',
 'than',
 'where',
 'aren',
 "we're",
 'being',
 'no',
 'themselves',
 "wouldn't",
 've',
 "that'll",
 'has',
 'such',
 'it',
 'you',
 'only',
 'is']

In [ ]:
#tokenization
nltk.download('punkt_tab')

from nltk.tokenize import word_tokenize # Import word_tokenize
word_token=[word_tokenize(i) for i in x_train]

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [ ]:
word_token

[['i',
  'fear',
  'that',
  'other',
  'people',
  'ask',
  'me',
  'about',
  'my',
  'feelings',
  'i',
  'am',
  'most',
  'reluctant',
  'to',
  'talk',
  'about',
  'things'],
 ['ive',
  'been',
  'thinking',
  'about',
  'what',
  'it',
  'is',
  'that',
  'drives',
  'me',
  'not',
  'only',
  'with',
  'fashion',
  'as',
  'pretentious',
  'as',
  'this',
  'is',
  'gon',
  'na',
  'make',
  'me',
  'sound',
  'i',
  'am',
  'studying',
  'fashion',
  'design',
  'so',
  'i',
  'do',
  'feel',
  'its',
  'kinda',
  'vital',
  'to',
  'understand',
  'what',
  'im',
  'trying',
  'to',
  'do',
  'there',
  'but',
  'in',
  'life',
  'as',
  'a',
  'whole'],
 ['i', 'love', 'comments', 'so', 'feel', 'free'],
 ['i',
  'feel',
  'irritable',
  'like',
  'no',
  'other',
  'and',
  'running',
  'will',
  'def',
  'cure',
  'that'],
 ['i',
  'dont',
  'have',
  'a',
  'yeast',
  'infection',
  'in',
  'the',
  'vagina',
  'i',
  'could',
  'be',
  'feeling',
  'irritated',
  'by',
  'yeast',
  'due',
  'to',
  'my',
  'diet',
  'so',
  'i',
  'should',
  'stop',
  'eating',
  'lots',
  'of',
  'sugary',
  'foods',
  'if',
  'i',
  'can'],
 ['i', 'just', 'feel', 'really', 'violent', 'right', 'now'],
 ['i',
  'can',
  'get',
  'away',
  'these',
  'days',
  'with',
  'the',
  'gag',
  'line',
  'when',
  'i',
  'feel',
  'like',
  'being',
  'sarcastic',
  'that',
  'i',
  'feel',
  'sorry',
  'for',
  'anyone',
  'who',
  'wasn',
  't',
  'fortunate',
  'enough',
  'to',
  'be',
  'born',
  'mexican'],
 ['i',
  'am',
  'feeling',
  'very',
  'anxious',
  'about',
  'going',
  'to',
  'therapy',
  'w'],
 ['i',
  'feel',
  'im',
  'just',
  'so',
  'greedy',
  'that',
  'all',
  'i',
  'care',
  'about',
  'is',
  'myself'],
 ['i',
  'feel',
  'like',
  'this',
  'another',
  'one',
  'of',
  'the',
  'more',
  'underrated',
  'records',
  'on',
  'the',
  'album',
  'not',
  'going',
  'to',
  'be',
  'the',
  'most',
  'popular',
  'but',
  'an',
  'amazing',
  'record',
  'nonetheless'],
 ['i',
  'feel',
  'like',
  'im',
  'almost',
  'uh',
  'afraid',
  'of',
  'everything',
  'so',
  'to',
  'speak'],
 ['i',
  'feel',
  'tortured',
  'the',
  'one',
  'thing',
  'i',
  'love',
  'is',
  'the',
  'one',
  'thing',
  'that',
  'wont',
  'support',
  'me',
  'financially',
  'but',
  'i',
  'cringe',
  'when',
  'i',
  'think',
  'of',
  'spending',
  'years',
  'chained',
  'to',
  'a',
  'desk',
  'performing',
  'a',
  'job',
  'by',
  'wrote',
  'with',
  'little',
  'or',
  'no',
  'room',
  'for',
  'creativity',
  'or',
  'for',
  'anything',
  'else',
  'that',
  'matters'],
 ['i', 'was', 'feeling', 'quite', 'nervous'],
 ['i',
  'get',
  'this',
  'sudden',
  'feeling',
  'that',
  'i',
  'am',
  'completely',
  'annoyed',
  'at',
  'him'],
 ['ive',
  'been',
  'feeling',
  'really',
  'spiteful',
  'lately',
  'so',
  'i',
  'think',
  'ill',
  'just',
  'sit',
  'here',
  'and',
  'listen',
  'to',
  'rammstein'],
 ['i',
  'feel',
  'quite',
  'uncertain',
  'that',
  'the',
  'art',
  'i',
  'create',
  'and',
  'my',
  'personal',
  'brand',
  'of',
  'creative',
  'living',
  'are',
  'what',
  'im',
  'here',
  'to',
  'contribute'],
 ['i',
  'only',
  'have',
  'to',
  'think',
  'about',
  'a',
  'high',
  'school',
  'experience',
  'and',
  'i',
  'instantly',
  'feel',
  'like',
  'that',
  'shy',
  'confused',
  'and',
  'terrorised',
  'teenager',
  'again'],
 ['i',
  'am',
  'feeling',
  'unsure',
  'about',
  'my',
  'words',
  'but',
  'it',
  'also',
  'means',
  'i',
  'am',
  'writing',
  'which',
  'is',
  'good'],
 ['i',
  'feel',
  'equally',
  'morally',
  'outraged',
  'regardless',
  'of',
  'whether',
  'its',
  'michigans',
  'or',
  'new',
  'yorks',
  'governor',
  'sleeping',
  'with',
  'prostitutes',
  'behind',
  'his',
  'wifes',
  'and',
  'daughters',
  'backs'],
 ['i',
  'didn',
  't',
  'have',
  'feelings',
  'for',
  'them',
  'but',
  'seriously',
  'after',
  'a',
  'while',
  'how',
  'do',
  'you',
  'feel',
  'love',
  'for',
  'someone',
  'who',
  'treats',
  'you',
  'with',
  'such',
  'disregard',
  'i',
  'was',
  'faithful',
  'and',
  'loyal'],
 ['ive',
  'found',
  'it',
  'has',
  'made',
  'a',
  'huge',
  'difference',
  'especially',
  'on',
  'the',
  'finger',
  'with',
  'my',
  'ring',
  'and',
  'the',
  'my',
  'skin',
  'feels',
  'so',
  'much',
  'softer',
  'and',
  'less',
  'irritated'],
 ['i',
  'feel',
  'pleased',
  'but',
  'at',
  'the',
  'same',
  'time',
  'i',
  'really',
  'don',
  't',
  'understand',
  'why',
  'do',
  'we',
  'feel',
  'this',
  'patriotism',
  'only',
  'twice',
  'every',
  'year'],
 ['i',
  'am',
  'really',
  'not',
  'expecting',
  'it',
  'somehow',
  'it',
  'made',
  'me',
  'feel',
  'shy',
  'but',
  'then',
  'it',
  's',
  'been',
  'a',
  'while',
  'part'],
 ['im',
  'feeling',
  'rather',
  'bothered',
  'because',
  'my',
  'physical',
  'and',
  'mental',
  'clock',
  'is',
  'still',
  'in',
  'october'],
 ['i',
  'grin',
  'and',
  'kiss',
  'my',
  'way',
  'down',
  'his',
  'body',
  'the',
  'same',
  'way',
  'he',
  'd',
  'done',
  'to',
  'me',
  'except',
  'with',
  'less',
  'teeth',
  'because',
  'i',
  'm',
  'feeling',
  'rather',
  'mellow',
  'and',
  'content',
  'at',
  'the',
  'moment'],
 ['i',
  'feel',
  'that',
  'if',
  'he',
  'hadnt',
  'appeared',
  'out',
  'of',
  'nowhere',
  'and',
  'distracted',
  'me',
  'i',
  'would',
  'have',
  'noticed',
  'the',
  'light',
  'change',
  'and',
  'none',
  'of',
  'this',
  'would',
  'have',
  'happened'],
 ['i',
  'feel',
  'like',
  'i',
  'enter',
  'his',
  'class',
  'petrified',
  'that',
  'im',
  'going',
  'to',
  'do',
  'or',
  'say',
  'something',
  'that',
  'will',
  'make',
  'him',
  'think',
  'less',
  'of',
  'me'],
 ['i', 'feel', 'innocent', 'and', 'free', 'again'],
 ['i',
  'sympathize',
  'with',
  'this',
  'person',
  'but',
  'i',
  'also',
  'feel',
  'a',
  'bit',
  'skeptical',
  'the',
  'theme',
  'is',
  'loss',
  'because',
  'everyone',
  'looses'],
 ['im',
  'not',
  'going',
  'to',
  'lie',
  'sometimes',
  'hearing',
  'myself',
  'say',
  'some',
  'of',
  'the',
  'things',
  'on',
  'my',
  'recordings',
  'makes',
  'me',
  'feel',
  'weird',
  'and',
  'insecure',
  'but',
  'just',
  'like',
  'the',
  'quote',
  'states',
  'above',
  'its',
  'a',
  'good',
  'thing'],
 ['i',
  'feel',
  'i',
  'wear',
  'what',
  'i',
  'wear',
  'to',
  'show',
  'other',
  'girls',
  'at',
  'my',
  'school',
  'who',
  'are',
  'timid',
  'when',
  'it',
  'comes',
  'to',
  'fashion',
  'that',
  'you',
  'won',
  't',
  'look',
  'weird',
  'if',
  'you',
  'walk',
  'around',
  'with',
  'your',
  'head',
  'held',
  'high'],
 ['i',
  'think',
  'a',
  'lot',
  'of',
  'the',
  'fun',
  'there',
  'is',
  'in',
  'meeting',
  'the',
  'players',
  'expectation',
  'and',
  'making',
  'the',
  'player',
  'feel',
  'clever',
  'making',
  'it',
  'seem',
  'like',
  'they',
  're',
  'not',
  'just',
  'clicking',
  'on',
  'an',
  'option',
  'you',
  'know'],
 ['i',
  'try',
  'to',
  'approach',
  'this',
  'thing',
  'called',
  'nature',
  'which',
  'is',
  'something',
  'im',
  'feeling',
  'a',
  'bit',
  'envious',
  'about'],
 ['i',
  'know',
  'im',
  'quite',
  'selfish',
  'but',
  'sometimes',
  'i',
  'feel',
  'like',
  'i',
  'dont',
  'want',
  'to',
  'throw',
  'everything',
  'just',
  'for',
  'something',
  'that',
  'is',
  'uncertain'],
 ['i',
  'refuse',
  'to',
  'rate',
  'the',
  'book',
  'but',
  'if',
  'she',
  'and',
  'her',
  'publisher',
  'feel',
  'snobbish',
  'then',
  'take',
  'it',
  'from',
  'me',
  'when',
  'i',
  'say',
  'jeanette',
  'winterson',
  'can',
  'not',
  'write',
  'and',
  'essentially',
  'does',
  'not',
  'do',
  'wish',
  'to',
  'do',
  'anything',
  'with',
  'the',
  'scope',
  'to',
  'explore'],
 ['im',
  'afraid',
  'im',
  'in',
  'an',
  'environment',
  'that',
  'makes',
  'me',
  'feel',
  'more',
  'relaxed',
  'cause'],
 ['i',
  'wish',
  'i',
  'knew',
  'how',
  'he',
  'was',
  'really',
  'feeling',
  'aside',
  'from',
  'reading',
  'the',
  'nervous',
  'twitches'],
 ['i', 'this', 'feels', 'rebellious', 'to', 'me'],
 ['i',
  'still',
  'think',
  'it',
  'is',
  'worth',
  'posting',
  'here',
  'as',
  'a',
  'reminder',
  'for',
  'the',
  'next',
  'time',
  'i',
  'feel',
  'anxious'],
 ['i',
  'feel',
  'completely',
  'unsure',
  'of',
  'any',
  'boundaries',
  'or',
  'normalcy'],
 ['i', 'was', 'feeling', 'extremely', 'anxious'],
 ['ill',
  'write',
  'a',
  'bunch',
  'youll',
  'respond',
  'and',
  'then',
  'ill',
  'back',
  'off',
  'in',
  'part',
  'because',
  'i',
  'feel',
  'shy'],
 ['i',
  'am',
  'posting',
  'about',
  'a',
  'past',
  'event',
  'where',
  'i',
  'am',
  'feeling',
  'like',
  'i',
  'should',
  'be',
  'insulted'],
 ['i',
  'suspect',
  'i',
  'was',
  'also',
  'dealing',
  'with',
  'caffeine',
  'withdrawal',
  'but',
  'i',
  'think',
  'i',
  'have',
  'now',
  'figured',
  'out',
  'a',
  'system',
  'of',
  'eating',
  'which',
  'works',
  'well',
  'for',
  'me',
  'and',
  'i',
  'feel',
  'fab'],
 ['i',
  'woke',
  'up',
  'feeling',
  'shaky',
  'and',
  'nauseous',
  'with',
  'lots',
  'of',
  'cramping',
  'and',
  'pressure',
  'in',
  'my',
  'abdomen',
  'and',
  'pelvis'],
 ['i',
  'feel',
  'like',
  'that',
  'leaves',
  'me',
  'as',
  'the',
  'artistic',
  'equivalent',
  'of',
  'the',
  'crack',
  'between',
  'couch',
  'cushions'],
 ['i',
  'will',
  'say',
  'that',
  'a',
  'little',
  'piece',
  'of',
  'me',
  'feels',
  'agitated',
  'when',
  'i',
  'watch',
  'discussions',
  'on',
  'race',
  'and',
  'there',
  'will',
  'i',
  'style',
  'color',
  'font',
  'family',
  'georgia',
  'serif',
  'font',
  'size',
  'px',
  'line',
  'height'],
 ['i',
  'left',
  'feeling',
  'helpless',
  'and',
  'more',
  'than',
  'a',
  'little',
  'sad'],
 ['i',
  'am',
  'friendly',
  'and',
  'so',
  'easy',
  'to',
  'talk',
  'to',
  'if',
  'only',
  'you',
  'are',
  'open',
  'to',
  'knowing',
  'me',
  'as',
  'a',
  'friend',
  'and',
  'not',
  'from',
  'a',
  'top',
  'down',
  'approach',
  'cos',
  'i',
  'feel',
  'intimidated',
  'and',
  'when',
  'i',
  'only',
  'know',
  'i',
  'do',
  'not',
  'want',
  'to',
  'offend',
  'somebody',
  'i',
  'shut',
  'up'],
 ['realizing',
  'that',
  'a',
  'friend',
  'had',
  'been',
  'talked',
  'into',
  'signing',
  'a',
  'certain',
  'contract'],
 ['i',
  'always',
  'feel',
  'i',
  'always',
  'understand',
  'that',
  'the',
  'people',
  'who',
  'are',
  'being',
  'the',
  'most',
  'hateful',
  'and',
  'harmful',
  'towards',
  'me',
  'are',
  'hurting',
  'themselves',
  'and',
  'taught',
  'wrongly',
  'and',
  'i',
  'hurt',
  'for',
  'them',
  'because',
  'i',
  'want',
  'to',
  'go',
  'back',
  'and',
  'undo',
  'the',
  'pain',
  'and',
  'childhood',
  'bigotry',
  'that',
  'binds',
  'their',
  'lives',
  'into',
  'this',
  'path'],
 ['i',
  'think',
  'just',
  'noticing',
  'this',
  'in',
  'me',
  'that',
  'i',
  'm',
  'more',
  'prone',
  'to',
  'feel',
  'jealous',
  'right',
  'now',
  'is',
  'helping',
  'me',
  'show',
  'up',
  'with',
  'a',
  'bit',
  'more',
  'intentionality',
  'than',
  'at',
  'other',
  'times',
  'in',
  'my',
  'life'],
 ['i',
  'wasn',
  't',
  'thinking',
  'negatively',
  'about',
  'any',
  'of',
  'those',
  'things',
  'often',
  'the',
  'feeling',
  'was',
  'benign',
  'or',
  'actually',
  'an',
  'excited',
  'anticipation'],
 ['i', 'remember', 'feeling', 'frantic', 'at', 'this', 'point'],
 ['i',
  'feel',
  'like',
  'i',
  'can',
  'trust',
  'them',
  'though',
  'seeing',
  'how',
  'they',
  'can',
  'understand',
  'how',
  'other',
  'women',
  'can',
  'be',
  'bitchy',
  'and',
  'neither',
  'of',
  'us',
  'want',
  'to',
  'deal',
  'with',
  'that',
  'shit'],
 ['id',
  'gotten',
  'the',
  'feeling',
  'that',
  'her',
  'friend',
  'hated',
  'me',
  'deeply',
  'for',
  'whatever',
  'id',
  'done',
  'to',
  'her'],
 ['ive', 'been', 'feeling', 'immensely', 'overwhelmed'],
 ['i',
  'do',
  'not',
  'believe',
  'guns',
  'are',
  'the',
  'solution',
  'to',
  'feeling',
  'afraid'],
 ['i',
  'feel',
  'so',
  'honored',
  'that',
  'students',
  'come',
  'to',
  'my',
  'classes'],
 ['i', 'feel', 'fine', 'read', 'the', 'rest'],
 ['i',
  'hate',
  'the',
  'way',
  'mom',
  'and',
  'dad',
  'are',
  'to',
  'her',
  'i',
  'hate',
  'the',
  'neglect',
  'of',
  'her',
  'feelings',
  'and',
  'her',
  'needs',
  'as',
  'an',
  'intelligent',
  'child',
  'that',
  'are',
  'rampant',
  'in',
  'their',
  'parenting',
  'style'],
 ['i',
  'was',
  'feeling',
  'pretty',
  'grumpy',
  'at',
  'this',
  'point',
  'but',
  'for',
  'whatever',
  'reason',
  'seeing',
  'this',
  'flower',
  'made',
  'me',
  'very',
  'happy'],
 ['i', 'go', 'to', 'bed', 'feeling', 'very', 'distraught', 'otherwise'],
 ['i',
  'suddenly',
  'feel',
  'anxious',
  'im',
  'crying',
  'over',
  'little',
  'things'],
 ['i', 'don', 't', 'feel', 'that', 'irritated'],
 ['i',
  'was',
  'feeling',
  'grouchy',
  'and',
  'the',
  'old',
  'man',
  'has',
  'mentioned',
  'that',
  'retail',
  'therapy',
  'is',
  'great'],
 ['im',
  'going',
  'to',
  'sleep',
  'now',
  'while',
  'i',
  'still',
  'feel',
  'triumphant'],
 ['im',
  'looking',
  'good',
  'and',
  'feeling',
  'good',
  'other',
  'than',
  'this',
  'crappy',
  'cold',
  'im',
  'dealing',
  'with'],
 ['i',
  'am',
  'feeling',
  'a',
  'bit',
  'doubtful',
  'of',
  'myself',
  'the',
  'last',
  'couple',
  'of',
  'weeks'],
 ['i',
  'didnt',
  'feel',
  'safe',
  'in',
  'my',
  'room',
  'because',
  'the',
  'argument',
  'was',
  'going',
  'on',
  'in',
  'my',
  'room',
  'and',
  'things',
  'were',
  'getting',
  'rough'],
 ['i',
  'may',
  'be',
  'starting',
  'to',
  'feel',
  'paranoid',
  'or',
  'maybe',
  'insecure',
  'but',
  'im',
  'just',
  'a',
  'mere',
  'human',
  'being',
  'who',
  'yearns',
  'to',
  'be',
  'loved',
  'to',
  'be',
  'cared',
  'of',
  'and',
  'to',
  'be',
  'noticed'],
 ['i',
  'am',
  'not',
  'strong',
  'that',
  'i',
  'feel',
  'scared',
  'lonely',
  'lost',
  'and',
  'confused'],
 ['im',
  'happy',
  'to',
  'have',
  'this',
  'in',
  'my',
  'kitchen',
  'but',
  'it',
  'feels',
  'like',
  'someone',
  'rushed',
  'this',
  'out',
  'and',
  'cut',
  'corners'],
 ['during', 'the', 'weekend', 'at', 'home'],
 ['im', 'feeling', 'so', 'so', 'insecure'],
 ['i',
  'feel',
  'pressured',
  'to',
  'come',
  'up',
  'with',
  'something',
  'else',
  'funny',
  'to',
  'write',
  'about'],
 ['i',
  'really',
  'like',
  'the',
  'job',
  'so',
  'far',
  'and',
  'i',
  'feel',
  'like',
  'i',
  'am',
  'genuinely',
  'putting',
  'some',
  'good',
  'out',
  'into',
  'the',
  'world'],
 ['i',
  'drove',
  'dannika',
  'to',
  'school',
  'i',
  'was',
  'feeling',
  'a',
  'little',
  'bit',
  'rushed',
  'and',
  'this',
  'is',
  'what',
  'greeted',
  'me',
  'as',
  'i',
  'turned',
  'the',
  'corner'],
 ['i', 'feel', 'more', 'clever'],
 ['i', 'usually', 'start', 'feeling', 'anxious'],
 ['i', 'feel', 'pressured', 'to', 'talk', 'to', 'them'],
 ['i',
  'thinks',
  'this',
  'chiefs',
  'ccw',
  'should',
  'be',
  'yanked',
  'by',
  'the',
  'state',
  'as',
  'i',
  'feel',
  'threatened'],
 ['i', 'feel', 'petrified', 'about', 'his', 'future'],
 ['i',
  'get',
  'the',
  'feeling',
  'that',
  'nellie',
  'is',
  'satisfied',
  'that',
  'the',
  'phone',
  'rang',
  'happy',
  'that',
  'leslie',
  'is',
  'out',
  'of',
  'the',
  'room',
  'now'],
 ['i',
  'feel',
  'that',
  'uncertain',
  'should',
  'be',
  'a',
  'better',
  'communicator'],
 ['i',
  'feel',
  'really',
  'successful',
  'for',
  'the',
  'fact',
  'that',
  'i',
  'read',
  'series',
  'books',
  'this',
  'summer',
  'that',
  'actually',
  'counted',
  'for',
  'the',
  'challenge',
  'finishing',
  'six',
  'total',
  'series'],
 ['i',
  'see',
  'other',
  'people',
  'writing',
  'about',
  'love',
  'when',
  'they',
  'have',
  'just',
  'brokeup',
  'and',
  'finding',
  'another',
  'person',
  'in',
  'his',
  'her',
  'life',
  'i',
  'kinda',
  'feel',
  'so',
  'disgusted'],
 ['i',
  'were',
  'to',
  'create',
  'a',
  'piece',
  'similar',
  'to',
  'this',
  'again',
  'i',
  'would',
  'improve',
  'on',
  'it',
  'by',
  'spending',
  'more',
  'time',
  'on',
  'the',
  'background',
  'as',
  'i',
  'feel',
  'i',
  'rushed',
  'this',
  'and',
  'it',
  'could',
  'have',
  'been',
  'more',
  'detailed'],
 ['i',
  'was',
  'feeling',
  'stressed',
  'or',
  'run',
  'down',
  'to',
  'support',
  'the',
  'immune',
  'system'],
 ['i', 'feel', 'a', 'bit', 'pissed', 'off', 'because', 'we', 'went', 'first'],
 ['i',
  'prayed',
  'for',
  'love',
  'for',
  'the',
  'people',
  'that',
  'i',
  'was',
  'feeling',
  'bitter',
  'towards',
  'and',
  'that',
  'they',
  'would',
  'find',
  'what',
  'was',
  'best',
  'for',
  'them'],
 ['i', 'feel', 'our', 'hearts', 'are', 'treading', 'dangerous', 'territory'],
 ['i', 'feel', 'i', 'really', 'wronged', 'commodore'],
 ['im',
  'not',
  'emo',
  'ing',
  'no',
  'no',
  'no',
  'haha',
  'i',
  'am',
  'feeling',
  'happy',
  'instead',
  'for',
  'being',
  'able',
  'to',
  'meet',
  'up',
  'with',
  'them'],
 ['i',
  'was',
  'the',
  'compere',
  'at',
  'a',
  'party',
  'and',
  'all',
  'my',
  'efforts',
  'to',
  'get',
  'the',
  'show',
  'rolling',
  'were',
  'thwarted',
  'by',
  'the',
  'immobile'],
 ['i',
  'kinda',
  'feel',
  'like',
  'being',
  'rebellious',
  'a',
  'libertine',
  'you',
  'know'],
 ['i',
  'feel',
  'that',
  'educating',
  'families',
  'and',
  'supporting',
  'and',
  'educationg',
  'mamas',
  'and',
  'papas',
  'is',
  'key'],
 ['i',
  'wear',
  'this',
  'shirt',
  'i',
  'feel',
  'artistic',
  'you',
  'are',
  'artistic',
  'but',
  'now',
  'i',
  'look',
  'artistic',
  'yes',
  'son',
  'you',
  'do'],
 ['i',
  'feel',
  'like',
  'having',
  'that',
  'sweet',
  'carby',
  'yet',
  'low',
  'glycemic',
  'meal',
  'not',
  'just',
  'at',
  'breakfast',
  'but',
  'often',
  'for',
  'dessert'],
 ['i',
  'could',
  'sense',
  'that',
  'he',
  'was',
  'uncomfortable',
  'when',
  'he',
  'came',
  'to',
  'deliver',
  'the',
  'letter',
  'but',
  'i',
  'was',
  'willing',
  'to',
  'attribute',
  'to',
  'him',
  'feeling',
  'weird',
  'about',
  'being',
  'so',
  'romantic',
  'and',
  'vulnerable'],
 ['i', 'feel', 'so', 'vulnerable'],
 ['i',
  'am',
  'feeling',
  'envious',
  'of',
  'other',
  'nations',
  'that',
  'despite',
  'the',
  'very',
  'small',
  'land'],
 ['i', 'woke', 'up', 'feeling', 'cranky', 'this', 'morning'],
 ['i',
  'will',
  'close',
  'my',
  'eyes',
  'and',
  'recite',
  'the',
  'following',
  'mantra',
  'every',
  'day',
  'and',
  'whenever',
  'i',
  'm',
  'feeling',
  'unsure',
  'frustrated',
  'or',
  'shiftless',
  'with',
  'my',
  'progress',
  'towards',
  'my',
  'top',
  'body'],
 ['i',
  'feel',
  'reluctant',
  'to',
  'talk',
  'about',
  'an',
  'issue',
  'which',
  'is',
  'so',
  'immediate',
  'especially',
  'as',
  'one',
  'can',
  'not',
  'make',
  'too',
  'much',
  'of',
  'a',
  'difference',
  'about',
  'it',
  'individually',
  'but',
  'what',
  'i',
  'can',
  'do',
  'is',
  'to',
  'spread',
  'the',
  'word'],
 ['im',
  'continually',
  'feeling',
  'triggered',
  'im',
  'not',
  'sure',
  'if',
  'people',
  'are',
  'insensitive',
  'or',
  'if',
  'im',
  'selfish',
  'most',
  'likely',
  'the',
  'latter'],
 ['i',
  'am',
  'baffled',
  'hurt',
  'that',
  'i',
  'feel',
  'assaulted',
  'and',
  'unsafe'],
 ['i',
  'have',
  'a',
  'feeling',
  'she',
  'is',
  'going',
  'to',
  'be',

In [ ]:
len(word_token)

4749

In [ ]:
# Remove stopwords from each sublist in word_token
filtered_tokens_train = [[word for word in sublist if word not in stop_words] for sublist in word_token]

# Display the first sublist of filtered tokens after removing stopwords
print(filtered_tokens_train[0])

['fear', 'people', 'ask', 'feelings', 'reluctant', 'talk', 'things']

In [ ]:
print(filtered_tokens_train[0])

['fear', 'people', 'ask', 'feelings', 'reluctant', 'talk', 'things']

**Vectorization Word2Vec - Skipgram**

In [ ]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 46.7 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [ ]:
import gensim
from gensim.models import Word2Vec
model_skipgram = gensim.models.Word2Vec(filtered_tokens_train, min_count = 1,vector_size = 100, window = 3, sg=1)

In [ ]:
vocabulary_skipgram = model_skipgram.wv.index_to_key
word_vec_dict={}
for word in vocabulary_skipgram:
    word_vec_dict[word]=model_skipgram.wv.get_vector(word)
print("The no of key-value pairs : ",len(word_vec_dict)) # should come equal to vocab size

The no of key-value pairs :  7769

In [ ]:
word_vec_dict

{'feel': array([-0.05340518,  0.1610322 ,  0.06696089,  0.2732674 , -0.05781319,
        -0.4309587 ,  0.15834571,  0.593173  , -0.10689011, -0.15427607,
        -0.0419978 , -0.2712075 , -0.06696089,  0.20525706,  0.13940112,
        -0.13165042,  0.10534748, -0.16642924, -0.04328715, -0.51980895,
         0.13803364,  0.18264754,  0.20897028, -0.14729239,  0.03468009,
         0.03073331, -0.20209962,  0.01706326, -0.276194  ,  0.05129768,
         0.25870502,  0.10727558,  0.34160787, -0.14901966, -0.06451862,
         0.1343457 ,  0.2147035 , -0.11858265, -0.17199457, -0.3834832 ,
         0.04262262, -0.19251941, -0.16310519,  0.04724379,  0.08036602,
        -0.07967222, -0.09672153, -0.02063195,  0.0234614 ,  0.18842384,
         0.20743202, -0.14384754, -0.1310874 , -0.13922577, -0.14541289,
         0.02114739,  0.2099811 , -0.03827918, -0.14145727,  0.2770679 ,
         0.02268207,  0.1416258 , -0.12182491,  0.08067044, -0.22624192,
         0.24916406,  0.06809741,  0.17539093, -0.31052873,  0.27215865,
        -0.09311917,  0.02654554,  0.24681993, -0.11629981,  0.1335792 ,
         0.03286445,  0.02175636, -0.01509255, -0.15016054, -0.14834899,
        -0.18957621, -0.12414587, -0.06981348,  0.3644631 , -0.08187313,
         0.06092591,  0.06826321,  0.12244068,  0.33575377,  0.02384415,
         0.36724386,  0.17008425, -0.01275343, -0.02784963,  0.31817526,
         0.17993538,  0.07908189, -0.24232203,  0.1014336 , -0.09971444],
       dtype=float32),
 'feeling': array([-0.07671938,  0.17213573,  0.08280476,  0.24824168, -0.01073864,
        -0.42372343,  0.15868406,  0.61792517, -0.09997347, -0.14669248,
        -0.05535752, -0.27186427, -0.07069997,  0.22484304,  0.15525448,
        -0.12231957,  0.10685372, -0.17399919, -0.05485406, -0.49598226,
         0.13019098,  0.16509806,  0.22268234, -0.17529555,  0.05150116,
         0.0294314 , -0.1964582 , -0.00213027, -0.28079626,  0.07291567,
         0.28063384,  0.11310847,  0.29673937, -0.14753969, -0.05599268,
         0.15243155,  0.21607402, -0.07041369, -0.13943893, -0.34745646,
         0.09764612, -0.23608713, -0.17806436,  0.04995649,  0.07525092,
        -0.05730334, -0.04026866, -0.05615307,  0.01451987,  0.17214535,
         0.23196389, -0.17205748, -0.14541121, -0.12100495, -0.15318693,
         0.06580616,  0.22998874, -0.01849589, -0.14240406,  0.2766644 ,
         0.01929601,  0.15452294, -0.12123861,  0.07709483, -0.20132726,
         0.24892186,  0.1017862 ,  0.15749487, -0.269546  ,  0.2641838 ,
        -0.09508188,  0.02803325,  0.24541889, -0.06728183,  0.1321806 ,
         0.00652704, -0.03063852, -0.00715198, -0.1499544 , -0.11627077,
        -0.19335584, -0.10288917, -0.05465218,  0.3304629 , -0.06675397,
         0.05719423,  0.05769791,  0.11662072,  0.3505766 ,  0.00290875,
         0.36432773,  0.16521075, -0.0081813 , -0.06104556,  0.30993444,
         0.17837855,  0.11482317, -0.2667491 ,  0.06116312, -0.0983815 ],
       dtype=float32),
 'like': array([-0.05519923,  0.17505364,  0.04317139,  0.2542306 , -0.01855021,
        -0.4055621 ,  0.1472808 ,  0.60976607, -0.13689432, -0.14085923,
        -0.07223158, -0.27751997, -0.0395435 ,  0.20215617,  0.13851434,
        -0.1649687 ,  0.1107097 , -0.15822136, -0.05364262, -0.53420955,
         0.09267963,  0.1661854 ,  0.18780996, -0.16263415,  0.01183228,
         0.01574971, -0.17033432,  0.00471011, -0.2859612 ,  0.07628741,
         0.30814788,  0.09923134,  0.31435913, -0.15185218, -0.08345303,
         0.15319455,  0.18938154, -0.10580131, -0.19486497, -0.37276205,
         0.03694625, -0.20837376, -0.12845936,  0.06019545,  0.11187519,
        -0.10877489, -0.10093416, -0.03947993,  0.0130376 ,  0.17153691,
         0.23479562, -0.12732778, -0.14173254, -0.15314116, -0.20528664,
         0.0208245 ,  0.18668592, -0.04886989, -0.15817606,  0.2593242 ,
         0.03488919,  0.11540519, -0.07558831,  0.09471395, -0.24528201,
         0.26519054,  0.11636986,  0.18433534, -0.33316278,  0.28157872,
        -0.10516738,  0.02487768,  0.25211802, -0.08813074,  0.14273666,
         0.04859523,  0.03694629, -0.01314783, -0.16900529, -0.09035238,
        -0.18661004, -0.15054572, -0.10401403,  0.36749518, -0.0978564 ,
         0.0560374 ,  0.04292109,  0.1455537 ,  0.36696008,  0.04456731,
         0.37145346,  0.18906319,  0.01080447, -0.03945155,  0.32240358,
         0.19094892,  0.11907662, -0.21914986,  0.14358114, -0.11680752],
       dtype=float32),
 'im': array([-0.07676064,  0.17651446,  0.07643271,  0.23976691, -0.00097043,
        -0.41744098,  0.17108214,  0.6171069 , -0.10386775, -0.15804306,
        -0.04434004, -0.26920813, -0.03999948,  0.17583035,  0.1623957 ,
        -0.15235761,  0.11411712, -0.20056356, -0.06717027, -0.48137453,
         0.13759336,  0.16430368,  0.2212128 , -0.1426819 ,  0.00199903,
         0.04106588, -0.18207246,  0.00221637, -0.25450918,  0.06736883,
         0.26323113,  0.11497968,  0.27333456, -0.13499284, -0.05712381,
         0.1687082 ,  0.21722344, -0.10175868, -0.16919489, -0.3640406 ,
         0.08234704, -0.22020034, -0.12471236,  0.04425559,  0.10146858,
        -0.0766748 , -0.04498216, -0.0609997 ,  0.01321187,  0.17011468,
         0.20697659, -0.15403877, -0.14605372, -0.14273979, -0.16963807,
         0.04552077,  0.21274534, -0.01484567, -0.12495322,  0.25307983,
         0.02759919,  0.1371363 , -0.08759926,  0.07035345, -0.20670854,
         0.22119068,  0.086794  ,  0.1913839 , -0.3017625 ,  0.23524019,
        -0.09002014,  0.02739442,  0.2459135 , -0.04876222,  0.129384  ,
         0.0032101 , -0.03164141,  0.01533194, -0.1747157 , -0.11246352,
        -0.20331857, -0.09745912, -0.08535548,  0.34697837, -0.07181365,
         0.06314865,  0.07001575,  0.16823688,  0.35311404, -0.00978436,
         0.36416516,  0.17692697, -0.01542458, -0.04509873,  0.32563874,
         0.18564174,  0.12936135, -0.27009144,  0.08509895, -0.11956395],
       dtype=float32),
 'know': array([-0.06103877,  0.17712379,  0.03860039,  0.25773218, -0.02634018,
        -0.41758323,  0.1507686 ,  0.61622036, -0.11753946, -0.13017535,
        -0.08171767, -0.27753794, -0.0569853 ,  0.19922031,  0.12860082,
        -0.14863136,  0.08954236, -0.18424769, -0.02380475, -0.542925  ,
         0.11879464,  0.17666616,  0.20510983, -0.13283472,  0.00876318,
         0.02823172, -0.19575474,  0.0093073 , -0.2976536 ,  0.08062942,
         0.31474417,  0.13573502,  0.32962045, -0.14660808, -0.0581098 ,
         0.13092312,  0.19273831, -0.12102468, -0.21030045, -0.39376876,
         0.04623513, -0.23052704, -0.15087289,  0.07011234,  0.10457055,
        -0.11795683, -0.08583932, -0.03565637,  0.01559605,  0.17566659,
         0.23923783, -0.12428675, -0.13014407, -0.1539267 , -0.18725774,
         0.02287556,  0.1720938 , -0.04676967, -0.14359306,  0.26750967,
         0.04146159,  0.12550174, -0.10825478,  0.09788492, -0.2420169 ,
         0.24072847,  0.10202154,  0.18328895, -0.33051297,  0.2901808 ,
        -0.12007194,  0.0235173 ,  0.24141604, -0.09156471,  0.13746618,
         0.05250785,  0.02034002, -0.01654776, -0.1606221 , -0.12462533,
        -0.19617634, -0.15795077, -0.0821343 ,  0.37389728, -0.10947371,
         0.05237748,  0.05937059,  0.16212912,  0.35860893,  0.02288538,
         0.38868973,  0.17747739,  0.00169197, -0.03794398,  0.31860134,
         0.16533859,  0.13893028, -0.2283878 ,  0.13121895, -0.10855428],
       dtype=float32),
 'little': array([-6.94729313e-02,  1.68635517e-01,  6.38942644e-02,  2.31949016e-01,
        -2.32451409e-02, -4.12562072e-01,  1.64969951e-01,  6.04891300e-01,
        -1.20452121e-01, -1.52665630e-01, -6.69741109e-02, -2.73073614e-01,
        -6.10037372e-02,  1.72897741e-01,  1.33464471e-01, -1.61504254e-01,
         8.68890285e-02, -1.90080687e-01, -5.65207601e-02, -5.02288580e-01,
         1.08182095e-01,  1.74094811e-01,  2.06278652e-01, -1.43262669e-01,
         3.84777482e-03,  2.36616228e-02, -1.79914668e-01, -1.66118089e-02,
        -2.66288936e-01,  7.41218254e-02,  2.84140468e-01,  1.01006240e-01,
         2.85040289e-01, -1.41665339e-01, -6.35088682e-02,  1.65494025e-01,
         2.05601826e-01, -9.78630111e-02, -1.66531697e-01, -3.72998148e-01,
         7.76554197e-02, -2.31024325e-01, -1.37215093e-01,  4.89672609e-02,
         9.37647447e-02, -9.43924189e-02, -6.95484132e-02, -3.81558537e-02,
         1.48636885e-02,  1.67060688e-01,  2.17561632e-01, -1.53459266e-01,
        -1.21435866e-01, -1.22711815e-01, -1.86735168e-01,  4.87643331e-02,
         2.12471589e-01, -3.96390297e-02, -1.42551497e-01,  2.48757645e-01,
         4.35875542e-02,  1.27854213e-01, -8.33025724e-02,  6.67323247e-02,
        -2.09547728e-01,  2.31314033e-01,  9.90938097e-02,  1.77260235e-01,
        -3.13645363e-01,  2.39809260e-01, -1.01100758e-01,  3.27209905e-02,
         2.49391496e-01, -6.78125620e-02,  1.35701954e-01,  3.10905501e-02,
        -1.43174548e-02,  3.60959966e-04, -1.62272677e-01, -9.65536237e-02,
        -1.79389209e-01, -1.22339524e-01, -7.94517398e-02,  3.36559683e-01,
        -7.56866857e-02,  5.16766272e-02,  4.56236191e-02,  1.63936630e-01,
         3.46881360e-01,  1.77738592e-02,  3.77987236e-01,  1.83226898e-01,
        -2.01793499e-02, -4.13986854e-02,  3.29933524e-01,  1.84490383e-01,
         1.17292389e-01, -2.51396954e-01,  1.04472749e-01, -1.16194300e-01],
       dtype=float32),
 'really': array([-0.05015258,  0.16264875,  0.05668941,  0.25525633, -0.02339701,
        -0.4075681 ,  0.1580181 ,  0.60475564, -0.11206023, -0.14271961,
        -0.06081463, -0.27004486, -0.04508863,  0.20690063,  0.1310586 ,
        -0.14037107,  0.1037032 , -0.17715646, -0.03519539, -0.51728487,
         0.11604225,  0.17179403,  0.2025192 , -0.14705224,  0.02063107,
         0.03201431, -0.19051675, -0.00475236, -0.27531496,  0.06878794,
         0.2896672 ,  0.13685514,  0.303576  , -0.13182393, -0.07554494,
         0.14696513,  0.1837034 , -0.11489643, -0.18947048, -0.38796362,
         0.06649142, -0.22332923, -0.12341449,  0.04711849,  0.09272233,
        -0.0860585 , -0.08644902, -0.05139005,  0.00992748,  0.16802101,
         0.21910866, -0.14674276, -0.14926223, -0.1393202 , -0.18800093,
         0.02494776,  0.18952051, -0.0455931 , -0.14689247,  0.25513753,
         0.03176871,  0.12974596, -0.09993225,  0.08775084, -0.22806656,
         0.24578601,  0.08035064,  0.16365272, -0.31779724,  0.2585293 ,
        -0.10844488,  0.03523206,  0.23967211, -0.08308473,  0.14087182,
         0.0235518 ,  0.01270317, -0.01168108, -0.16883254, -0.09710458,
        -0.17248282, -0.13921498, -0.09259328,  0.3622524 , -0.08827705,
         0.05708826,  0.0607343 ,  0.14620553,  0.34344923,  0.02382513,
         0.36961454,  0.18005776, -0.01484465, -0.03446805,  0.30643746,
         0.18076211,  0.12826148, -0.24274439,  0.11069935, -0.10205114],
       dtype=float32),
 'get': array([-0.04742804,  0.17371091,  0.06340097,  0.2722465 , -0.02928104,
        -0.42428938,  0.15807962,  0.6155422 , -0.10738284, -0.14736263,
        -0.07366953, -0.2861468 , -0.0392717 ,  0.191782  ,  0.13848013,
        -0.13937323,  0.10089484, -0.20039067, -0.04027097, -0.5392375 ,
         0.12431936,  0.1964757 ,  0.19494098, -0.1668296 ,  0.00363485,
         0.03863554, -0.19952953,  0.00824561, -0.29271823,  0.08453198,
         0.28994504,  0.14342792,  0.31757206, -0.14126664, -0.06992658,
         0.13664714,  0.18848917, -0.11743716, -0.20489198, -0.39825353,
         0.06898765, -0.22892365, -0.14644258,  0.06597166,  0.09903286,
        -0.11050881, -0.08781187, -0.04403256,  0.0223926 ,  0.17976068,
         0.21482895, -0.13727036, -0.13366559, -0.15553315, -0.1886192 ,
         0.05360062,  0.18532948, -0.02823135, -0.14209782,  0.28768945,
         0.0461021 ,  0.13514824, -0.12398733,  0.10376389, -0.23203158,
         0.24452135,  0.06969497,  0.18472506, -0.32446703,  0.26756632,
        -0.10724858,  0.01742591,  0.25462553, -0.10229787,  0.12628356,
         0.03636669,  0.01937456, -0.03412405, -0.16805461, -0.132793  ,
        -0.19001162, -0.14706345, -0.10103147,  0.3785099 , -0.0826688 ,
         0.06565074,  0.05688408,  0.17334673,  0.37651268,  0.02131167,
         0.38331398,  0.17815556, -0.01335293, -0.02364992,  0.31088623,
         0.17391431,  0.12551019, -0.24663824,  0.12363076, -0.12395108],
       dtype=float32),
 'time': array([-0.07221529,  0.1918188 ,  0.05880518,  0.27631375, -0.01406272,
        -0.42297918,  0.16583402,  0.61511034, -0.11073757, -0.1252471 ,
        -0.07199557, -0.2949157 , -0.0301456 ,  0.19832465,  0.15294537,
        -0.1450173 ,  0.08345269, -0.21273002, -0.04161811, -0.52567106,
         0.12170134,  0.20348082,  0.19954972, -0.16587803,  0.03114654,
         0.03440783, -0.20461304, -0.01063354, -0.28253508,  0.06792985,
         0.30815136,  0.13902073,  0.32153377, -0.11422595, -0.07355724,
         0.14316367,  0.19377524, -0.10568193, -0.1927055 , -0.4203258 ,
         0.05486593, -0.22518943, -0.14768791,  0.06267523,  0.08568531,
        -0.09795745, -0.07034053, -0.03813678,  0.00460788,  0.17435452,
         0.22647248, -0.13457948, -0.15056242, -0.14558175, -0.18375032,
         0.03652996,  0.20072992, -0.03303576, -0.13940579,  0.27251878,
         0.02700001,  0.1404176 , -0.11542854,  0.09498575, -0.24657957,
         0.23624098,  0.07630444,  0.17142567, -0.3294784 ,  0.28049722,
        -0.12770276,  0.02193481,  0.25497004, -0.09529244,  0.11514086,
         0.02945272, -0.00821661, -0.03592223, -0.18250512, -0.12388897,
        -0.17864344, -0.16346025, -0.07388652,  0.37096316, -0.07622153,
         0.07254499,  0.04491722,  0.15511389,  0.36986893,  0.03409523,
         0.3746899 ,  0.18705411, -0.00101501, -0.03740552,  0.32849872,
         0.18942454,  0.13223894, -0.23270221,  0.12214211, -0.12719423],
       dtype=float32),
 'people': array([-6.31395578e-02,  1.60522029e-01,  4.32488173e-02,  2.80713856e-01,
        -3.47928777e-02, -4.41134423e-01,  1.42170429e-01,  6.20121598e-01,
        -1.07163854e-01, -1.43530697e-01, -6.70014247e-02, -2.88201332e-01,
        -5.01772314e-02,  2.03148052e-01,  1.34191200e-01, -1.27404720e-01,
         1.00668997e-01, -2.11338058e-01, -2.35406421e-02, -5.33536792e-01,
         1.14905588e-01,  2.04447806e-01,  1.70874760e-01, -1.60891891e-01,
         3.03031653e-02,  2.21980959e-02, -2.09473178e-01,  1.53977694e-02,
        -2.88874596e-01,  6.66699708e-02,  3.14037353e-01,  1.42078191e-01,
         3.34642798e-01, -1.13055401e-01, -8.60674605e-02,  1.47185430e-01,
         1.96955889e-01, -1.18474945e-01, -2.00493589e-01, -3.92768919e-01,
         5.68082817e-02, -2.13066339e-01, -1.46085590e-01,  5.29645234e-02,
         8.98347721e-02, -1.04806274e-01, -9.02975053e-02, -3.11324541e-02,
         1.61707513e-02,  1.91208839e-01,  2.29428589e-01, -1.15702048e-01,
        -1.49559200e-01, -1.30841449e-01, -1.90017328e-01,  2.41838619e-02,
         1.83189511e-01, -4.00910378e-02, -1.31388932e-01,  2.69355476e-01,
         3.22009623e-02,  1.52377576e-01, -1.05079815e-01,  9.66421217e-02,
        -2.39018127e-01,  2.35689908e-01,  8.00857246e-02,  1.52245283e-01,
        -3.24323952e-01,  2.71357864e-01, -1.08532034e-01,  2.28251759e-02,
         2.36387819e-01, -1.21501833e-01,  1.35345697e-01,  3.12944464e-02,
         1.92158781e-02, -4.40891534e-02, -1.59158573e-01, -1.16986729e-01,
        -1.72948614e-01, -1.52637735e-01, -9.15196985e-02,  3.92254621e-01,
        -8.43752250e-02,  6.43250048e-02,  3.43817919e-02,  1.58615321e-01,
         3.75899494e-01,  4.24331352e-02,  3.72066528e-01,  1.94359526e-01,
        -3.32073105e-04, -1.62505414e-02,  3.23113382e-01,  1.66248024e-01,
         1.06047571e-01, -2.19807863e-01,  1.38420895e-01, -1.08335152e-01],
       dtype=float32),
 'want': array([-0.04743748,  0.16837923,  0.05733173,  0.25043404, -0.0386386 ,
        -0.4204578 ,  0.14260238,  0.6108267 , -0.11732242, -0.15309292,
        -0.06256014, -0.28704247, -0.02942178,  0.19473496,  0.13702251,
        -0.13317794,  0.09626763, -0.193901  , -0.02155849, -0.5358263 ,
         0.11393081,  0.18192765,  0.2014327 , -0.15110086,  0.0034734 ,
         0.03846529, -0.19743665, -0.00166573, -0.2730531 ,  0.0802464 ,
         0.28986958,  0.13878429,  0.33029628, -0.11979642, -0.05868099,
         0.14102101,  0.19514939, -0.11931937, -0.21630384, -0.39221847,
         0.04565059, -0.22313933, -0.14841054,  0.07344517,  0.07837685,
        -0.11650281, -0.09168179, -0.03633343,  0.00720992,  0.17579916,
         0.21615927, -0.12721848, -0.15449132, -0.15036117, -0.18237701,
         0.03327582,  0.18110712, -0.03943412, -0.12711307,  0.27542606,
         0.01926903,  0.13085496, -0.11627973,  0.09479812, -0.2488941 ,
         0.24268343,  0.07103398,  0.1555352 , -0.31037864,  0.26785994,
        -0.10790935,  0.0292535 ,  0.23765402, -0.08747439,  0.12734842,
         0.0550809 ,  0.02274295, -0.04051785, -0.17378949, -0.10951107,
        -0.17206901, -0.13576694, -0.07227909,  0.38862017, -0.10787133,
         0.06984158,  0.04651193,  0.16132143,  0.36917078,  0.03296759,
         0.38992718,  0.18466274, -0.01178035, -0.02061198,  0.29553488,
         0.17042209,  0.13945629, -0.24128151,  0.13128313, -0.12011299],
       dtype=float32),
 'bit': array([-0.04860031,  0.17415234,  0.06788985,  0.24320497, -0.01112971,
        -0.40636083,  0.15129927,  0.58824223, -0.10959722, -0.14077303,
        -0.05047049, -0.2561017 , -0.0537167 ,  0.1827482 ,  0.14452924,
        -0.1476371 ,  0.08878778, -0.18570916, -0.0562705 , -0.48903218,
         0.11140433,  0.15837331,  0.19572599, -0.1581964 ,  0.01332379,
         0.0188866 , -0.18657404,  0.00427214, -0.2516901 ,  0.07209921,
         0.26287475,  0.10128243,  0.28271943, -0.12736988, -0.0667653 ,
         0.15313673,  0.19428217, -0.09507348, -0.1717565 , -0.36341897,
         0.05782098, -0.21596193, -0.13166715,  0.05871353,  0.08515786,
        -0.07911938, -0.05037114, -0.05391629,  0.01347913,  0.17366558,
         0.2111534 , -0.14691867, -0.12361912, -0.12032066, -0.17459859,
         0.04214669,  0.19288288, -0.02608083, -0.1385863 ,  0.24664877,
         0.03720262,  0.13278113, -0.09500819,  0.07283104, -0.21310139,
         0.22818045,  0.10117805,  0.17644198, -0.30353948,  0.24763787,
        -0.10278413,  0.04542099,  0.23838091, -0.06528713,  0.13349372,
         0.02842723, -0.01839638,  0.00563554, -0.1578142 , -0.10544248,
        -0.18206501, -0.10059001, -0.08747777,  0.3274955 , -0.06491097,
         0.06271686,  0.04259214,  0.13728574,  0.34672284,  0.02054779,
         0.3633168 ,  0.16804324, -0.02198095, -0.03635558,  0.31559965,
         0.16818686,  0.10361268, -0.2405739 ,  0.08415876, -0.11111881],
       dtype=float32),
 'think': array([-5.74161708e-02,  1.67550161e-01,  6.45876229e-02,  2.54393190e-01,
        -2.14561913e-02, -4.14845049e-01,  1.46719798e-01,  6.26265943e-01,
        -9.16167274e-02, -1.39419407e-01, -8.42271000e-02, -2.91930437e-01,
        -5.53830378e-02,  1.96573138e-01,  1.36774436e-01, -1.50905699e-01,
         9.34172198e-02, -1.93859264e-01, -1.89900920e-02, -5.27161777e-01,
         1.17475927e-01,  1.91156015e-01,  1.89817548e-01, -1.40075803e-01,
         1.92136392e-02,  3.99042964e-02, -2.05308989e-01,  9.13599599e-03,
        -2.88736492e-01,  8.87889415e-02,  2.89440066e-01,  1.42504230e-01,
         3.19684267e-01, -1.30361959e-01, -7.76517615e-02,  1.26007229e-01,
         1.86956555e-01, -1.30221650e-01, -1.98962882e-01, -3.97695422e-01,
         5.07159494e-02, -2.16201931e-01, -1.45609617e-01,  5.96784726e-02,
         7.92415142e-02, -1.10777512e-01, -7.21569732e-02, -4.49318327e-02,
         2.49070628e-03,  1.89975575e-01,  2.36287266e-01, -1.39282867e-01,
        -1.41713038e-01, -1.53468028e-01, -1.87013447e-01,  3.01023070e-02,
         1.84158817e-01, -3.11065223e-02, -1.32823482e-01,  2.81442612e-01,

In [ ]:
max_sen_len= max_sen # max lenght of word in a sentence
vocab_size =35000  #ideally it should be len(tok.word_index) + 1  or total no of words in data in this case = 4750, but to handle number of data which not appear in train, for example in test, make the size higher
embed_dim=100 # embedding dimension as choosen in word2vec constructor

In [ ]:
#!pip install tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer # Import Tokenizer from the correct module in TensorFlow
#from keras.preprocessing.text import one_hot,Tokenizer
tok = Tokenizer()
tok.fit_on_texts(filtered_tokens_train) #create index for each token
vocab_size = vocab_size
encd_rev = tok.texts_to_sequences(filtered_tokens_train) #extract index only for each token

In [ ]:
encd_rev

[[566, 10, 281, 49, 117, 190, 25],
 [18,
  178,
  2211,
  1209,
  3386,
  1056,
  377,
  23,
  713,
  1388,
  1209,
  1210,
  1,
  567,
  602,
  228,
  4,
  82,
  26,
  126],
 [31, 603, 1, 207],
 [1, 104, 3, 378, 3387, 2212],
 [20,
  2213,
  2214,
  3388,
  22,
  2,
  155,
  2213,
  532,
  1693,
  111,
  456,
  714,
  2215,
  3389],
 [1, 7, 179, 30],
 [8, 61, 86, 3390, 764, 1, 3, 512, 1, 765, 165, 1694, 44, 1211, 2216],
 [2, 69, 21, 1695, 1389],
 [1, 4, 140, 282],
 [1, 3, 133, 16, 3391, 3392, 2217, 21, 312, 350, 2218, 2219],
 [1, 3, 4, 208, 2220, 89, 66, 568],
 [1,
  98,
  16,
  74,
  31,
  16,
  74,
  407,
  434,
  1696,
  2221,
  13,
  651,
  192,
  3393,
  1697,
  2222,
  243,
  766,
  6,
  294,
  1698,
  84,
  341,
  1390],
 [2, 58, 90],
 [8, 1699, 2, 295, 166],
 [18, 2, 7, 715, 283, 13, 180, 313, 533, 3394],
 [1, 58, 109, 652, 604, 605, 1700, 314, 379, 4, 2223],
 [13, 569, 220, 487, 1212, 1, 3, 221, 172, 3395, 1391],
 [2, 101, 342, 35, 435, 181, 33],
 [1,
  767,
  1701,
  408,
  1392,
  380,
  3396,
  134,
  3397,
  3398,
  848,
  3399,
  381,
  2224,
  3400,
  2225],
 [49, 488, 1, 31, 53, 1393, 3401, 716, 3402],
 [18, 209, 55, 606, 653, 229, 1394, 1395, 946, 40, 29, 3403, 52, 155],
 [1, 513, 9, 7, 228, 1, 3404, 2226, 62, 144],
 [7, 2227, 382, 55, 1, 221, 141],
 [4, 2, 112, 173, 768, 717, 1702, 19, 1703],
 [1704, 947, 17, 230, 17, 222, 948, 52, 1705, 2, 112, 534, 367, 135],
 [1, 849, 1706, 1707, 182, 15, 1213, 718, 284, 1396, 15, 436],
 [1, 3, 1397, 244, 769, 4, 21, 41, 24, 23, 13, 52],
 [1, 296, 207],
 [3405, 64, 35, 1, 12, 343, 3406, 1057, 156, 3407],
 [4, 21, 949, 79, 1398, 41, 25, 3408, 59, 1, 102, 121, 3, 1058, 1399, 33, 74],
 [1,
  315,
  315,
  197,
  719,
  220,
  607,
  316,
  1209,
  103,
  102,
  271,
  34,
  297,
  850,
  569],
 [13, 70, 383, 851, 1708, 1400, 113, 1401, 1, 330, 113, 457, 3, 3409, 1709, 5],
 [145, 852, 74, 458, 770, 24, 4, 2, 12, 272],
 [5, 4, 58, 122, 79, 1, 3, 20, 11, 853, 66, 24, 109],
 [1059,
  1710,
  193,
  3410,
  1,
  1711,
  75,
  41,
  3411,
  3412,
  96,
  1712,
  245,
  84,
  3413,
  1713],
 [4, 89, 4, 1060, 59, 1, 384, 570],
 [245, 409, 7, 2, 1714, 331, 90, 3414],
 [40, 273],
 [19, 13, 771, 608, 1715, 191, 9, 1, 69],
 [1, 295, 101, 2228, 3415],
 [2, 210, 69],
 [180, 96, 1214, 1716, 1717, 180, 27, 141, 1, 221],
 [608, 211, 654, 2, 3, 150],
 [1718, 35, 950, 1402, 3416, 13, 1719, 772, 456, 1061, 47, 1, 1062],
 [298, 2, 183, 1063, 714, 3417, 655, 3418, 3419],
 [1, 3, 951, 459, 3420, 3421, 1403, 3422],
 [41,
  6,
  854,
  40,
  51,
  535,
  2229,
  609,
  773,
  952,
  1720,
  167,
  3423,
  3424,
  1720,
  1215,
  1216,
  764,
  1721],
 [76, 2, 198, 6, 255],
 [536, 514, 190, 351, 332, 127, 855, 852, 856, 1, 223, 5, 11, 3425, 774, 775],
 [3426, 127, 857, 3427, 317, 2230],
 [38,
  1,
  38,
  228,
  10,
  385,
  2231,
  252,
  1404,
  1064,
  2232,
  299,
  11,
  32,
  27,
  3428,
  368,
  1405,
  3429,
  3430,
  437,
  610],
 [13, 3431, 2233, 1, 184, 30, 656, 197, 12, 3432, 114, 26],
 [178, 3433, 25, 168, 2, 2234, 67, 136, 1406],
 [87, 2, 231, 212],
 [1, 3, 410, 54, 369, 228, 411, 185, 953, 151, 11, 515, 571],
 [146, 776, 2, 127, 137, 611, 352, 146, 222],
 [18, 2, 2235, 105],
 [261, 3434, 2236, 2, 89],
 [1, 386, 489, 92, 1407],
 [1, 344, 106, 490],
 [152, 17, 274, 1065, 152, 2237, 49, 491, 572, 275, 3435, 1722, 773],
 [2, 39, 256, 212, 352, 232, 369, 1408, 55, 65],
 [32, 387, 2, 388, 1217],
 [353, 1, 69, 4, 777, 6, 25],
 [1, 155],
 [2, 438, 200, 318, 1218, 2238, 1695, 246],
 [4, 21, 186, 19, 1, 657],
 [4, 187, 33, 2, 33, 2239, 71, 4, 950],
 [2, 12, 300, 99, 573, 492],
 [60, 1, 285, 294, 1723, 21, 294, 25, 63, 3436],
 [80, 247, 1, 123, 233, 121, 4, 3437, 460, 3438, 345, 1724, 1213],
 [234, 1, 93, 574, 262, 172],
 [4, 65, 954, 40, 3, 53, 199, 955, 1725],
 [658, 85],
 [4, 2, 121],
 [1, 147, 92, 24, 341, 1066, 96],
 [7, 3, 243, 257, 1, 3, 858, 439, 33, 81],
 [1219, 3439, 220, 2, 6, 12, 199, 2240, 1220, 1067],
 [1, 330],
 [370, 124, 2, 69],
 [1, 147, 190],
 [1726, 3440, 3441, 3442, 778, 1, 174],
 [1, 769, 248],
 [8, 2, 3443, 440, 720, 3444, 65, 3445, 294],
 [1, 109, 77, 3446],
 [1, 7, 389, 301, 106, 721, 537, 722, 67, 2241, 956, 2242, 516, 1727, 721],
 [37, 10, 181, 31, 3447, 779, 133, 64, 26, 567, 1, 263],
 [604, 854, 1409, 15, 957, 651, 9, 1728, 1, 199, 22, 3448],
 [2, 169, 319, 434, 3449, 772],
 [1, 12, 128, 213, 83],
 [1729, 31, 10, 2, 201, 252, 15, 73, 235],
 [1, 1068, 3450, 138, 2243],
 [1, 7, 188, 3451],
 [4, 958, 3452, 1221, 2, 65, 390, 107, 493],
 [3453, 575, 2244, 8, 197, 2245, 3454, 3455],
 [567, 1, 3, 273, 3456, 5],
 [1, 1730, 1731, 538, 3457, 3458, 3459, 1069],
 [315, 1732, 1, 459, 459, 103, 459, 780, 612],
 [1, 3, 333, 3460, 115, 1070, 3461, 1733, 1734, 168, 2246],
 [22, 320, 118, 354, 2247, 1410, 1411, 3462, 2, 102, 3463, 119],
 [1, 119],
 [2, 272, 3464, 659, 334, 1222],
 [298, 2, 157, 224],
 [264,
  265,
  3465,
  1223,
  3466,
  62,
  28,
  660,
  2,
  101,
  148,
  3467,
  1071,
  252,
  855,
  230],
 [1, 117, 190, 859, 3468, 229, 16, 23, 29, 653, 3469, 2248, 461],
 [4, 3470, 2, 3471, 4, 56, 10, 2249, 4, 122, 1412, 1735],
 [2250, 299, 1, 517, 1736],
 [2, 21, 350, 959, 3, 2251, 1737],
 [19, 1, 3472, 333, 462],
 [391, 297, 61, 14, 1, 236],
 [228, 1, 3, 137, 142],
 [392, 1413, 392, 1727, 1738, 1738],
 [1, 169, 539, 412],
 [1, 90],
 [1072, 111, 286, 3473, 3474, 3475, 1, 6, 123],
 [146, 1, 77],
 [4, 33, 1739, 723, 49, 3476, 512, 3477],
 [50, 412, 1, 64, 1740, 413, 2252],
 [1, 330, 3478, 113, 4, 58, 2, 47, 44, 1224, 16],
 [83, 850, 3479, 409, 31, 569, 3480, 2253, 540, 249, 45, 2, 120, 9, 92, 2254],
 [2, 72, 1741, 194, 255],
 [1, 3, 4, 98, 3, 192, 441],
 [83, 9, 144, 2, 71],
 [1, 98, 860, 355, 462, 17, 127],
 [287,
  1,
  39,
  536,
  88,
  3481,
  3482,
  378,
  3483,
  232,
  20,
  129,
  571,
  3484,
  43,
  1742],
 [1225,
  1073,
  661,
  1226,
  781,
  613,
  21,
  168,
  35,
  1,
  12,
  221,
  3485,
  29,
  41,
  46,
  2255,
  10],
 [4, 236, 2, 123],
 [1, 302, 2256, 1743, 2257, 2258, 276, 3486],
 [1, 198, 107, 45, 2, 77, 235, 1744, 13, 3487, 274],
 [1, 54, 96, 168, 44, 3488, 26, 767, 321, 356],
 [4, 3489, 3490, 195, 59, 357, 1, 29, 662, 246, 663, 3491, 3492, 3493, 12],
 [1, 108, 351, 54, 214, 1745, 342, 568],
 [60, 1, 50, 1414, 117, 351, 7, 202, 21],
 [494,
  224,
  861,
  1074,
  40,
  288,
  1227,
  3494,
  713,
  3,
  3495,
  3496,
  158,
  194,
  1074,
  1415,
  2259],
 [23, 2260, 1416, 37, 13, 1, 3497, 72, 25],
 [1, 147, 41, 24],
 [3498,
  192,
  1746,
  492,
  441,
  30,
  862,
  193,
  43,
  261,
  207,
  1,
  409,
  1746,
  97,
  26,
  91,
  2261],
 [106, 863, 21, 3499, 2262, 1228, 3500, 3501, 266, 230, 23, 1, 104, 256],
 [137, 299, 49, 137, 1417, 774, 31, 137, 3502, 2263, 127, 7, 3503],
 [2, 438, 412, 277, 278, 21, 1747],
 [1, 463, 94, 3504, 1075, 78, 3505, 3506],
 [20, 5, 1, 101, 3507, 25, 229, 10],
 [289, 53, 1, 3, 36, 237, 190, 495, 170],
 [145,
  87,
  1058,
  1,
  80,
  1418,
  782,
  2264,
  14,
  576,
  319,
  5,
  9,
  73,
  238,
  614,
  3508],
 [494, 224, 2, 3, 86, 1748, 541, 8, 3509, 297, 1229, 3510],
 [853,
  77,
  180,
  1,
  2265,
  4,
  123,
  864,
  3511,
  30,
  1749,
  3512,
  1750,
  610,
  213,
  615,
  46],
 [8, 211, 2, 127, 2266, 26, 101, 2, 616, 225, 44],
 [1, 2267, 71, 1719, 724, 3513, 664, 1419],
 [1, 7, 104, 4, 1751],
 [36, 1076, 1077, 518, 26, 40, 71, 960],
 [130, 18, 496, 44, 143, 335, 9, 286, 603, 442, 1, 153],
 [1, 783, 1752, 1753, 1754, 275],
 [303, 2, 105, 665, 1755, 1756, 212, 215],
 [1, 19, 57],
 [1, 3, 4, 239],
 [4, 303, 777, 2, 367, 345, 21, 27, 777],
 [1230, 26, 145, 75, 322, 26, 42, 1, 89, 322],
 [18, 1, 33, 44, 42, 126, 1420, 617, 126, 28],
 [4, 295, 56, 1078, 3514, 44, 4, 2, 120, 107, 73, 577, 2268, 1757],
 [1, 666, 55, 865, 323],
 [2, 112, 459, 48, 3, 866, 3515],
 [1,
  1421,
  3516,
  3517,
  1422,
  3518,
  3519,
  3520,
  725,
  1423,
  1721,
  667,
  203,
  1079],
 [1758, 1, 1759, 110, 57, 252, 10],
 [324, 1, 236],
 [354, 61, 2269, 2270, 346, 3521, 142, 2, 542, 202, 867, 141, 437],
 [1, 302, 2256, 1743, 2257],
 [4, 3522, 249, 173, 2271, 59, 1, 3523, 258, 43, 173, 393],
 [83, 1760, 358, 1761, 59, 1, 726],
 [1, 39, 102, 961, 142, 1762, 3524, 134, 3525, 21, 727],
 [2, 101, 248],
 [1077, 1763, 3526, 1080, 1, 443, 51, 148, 1764, 394, 3527, 2272],
 [868, 2, 71, 543, 2, 664],
 [287, 38, 1, 184, 25, 1765, 1766, 359, 3528],
 [1, 58, 93, 42, 26, 1231, 124, 42, 3529],
 [1, 302, 158, 962, 3530],
 [533, 3531, 4, 2, 618, 155],
 [2, 226, 25, 869, 21, 32, 17, 11, 1424],
 [18, 2, 360, 283],
 [197, 49, 47, 167, 963, 393],
 [8, 2, 10, 13, 4, 360, 1767, 784, 870, 723, 1768, 197, 785],
 [4,
  544,
  30,
  1,
  3,
  36,
  11,
  202,
  6,
  464,
  659,
  463,
  3532,
  382,
  68,
  3533,
  23,
  1,
  77],
 [1, 12, 3, 3534, 304, 870, 726, 2],
 [395, 165, 95, 1, 290, 346, 1769, 497, 668, 9, 86],
 [96, 2, 65, 1767],
 [1232, 498, 3535, 860, 1, 109, 2273, 135, 3536, 187, 768, 2274],
 [3537, 669, 3538, 1, 3539, 964, 3540],
 [3541, 22, 313, 1081, 4, 2, 257, 273, 46, 1233, 4, 2, 57, 81, 9],
 [18, 1425, 157, 131, 4, 2, 19, 12, 1767, 125, 20, 5, 131, 1770, 24, 341],
 [4, 2, 6, 465, 248, 3, 3542, 38, 786, 11, 81, 8, 1082],
 [1771,
  361,
  1083,
  2275,
  21,
  92,
  27,
  2,
  185,
  22,
  670,
  466,
  48,
  3,
  1234,
  1235,
  3543],
 [5, 1, 174, 243, 14, 100, 192, 8, 7, 303, 3544, 8],
 [305, 1, 70, 204, 25, 45, 2276, 1084, 1731, 240],
 [31,
  2277,
  1085,
  787,
  1772,
  1236,
  1212,
  23,
  1,
  3545,
  3546,
  1734,
  3547,
  671,
  467,
  444,
  1426,
  414,
  299,
  393],
 [1, 188],
 [5, 1061, 619, 291, 2278, 965, 59, 151, 1, 1086, 14, 277, 3548],
 [250, 73, 17, 871, 3549, 1427, 91, 2, 850, 27, 110],
 [1, 152, 3, 68, 95, 137, 165, 3, 43, 111, 187, 3550, 3551],
 [11, 1, 109, 2279, 1773, 233, 2280, 1237, 1428],
 [4, 2, 62, 12, 715, 3552, 672, 114],
 [1, 671, 1429],
 [106, 1, 36, 106, 59, 6, 256],
 [3553, 3554, 3555, 2281, 211, 2282, 1430, 445, 1, 499, 415, 468, 241, 28],
 [88,
  3556,
  1431,
  204,
  1432,
  2283,
  1744,
  1238,
  872,
  1774,
  3557,
  1,
  251,
  866,
  42],
 [2284, 47, 130, 2284, 259, 1, 121, 9, 11, 500, 92, 1775, 728],
 [543, 1, 302, 2, 1087, 673, 1088],
 [4,
  2,
  36,
  534,
  73,
  24,
  2285,
  3558,
  4,
  468,
  2286,
  18,
  38,
  50,
  32,
  2287,
  143,
  8,
  3559],
 [35,
  31,
  369,
  1776,
  3560,
  1,
  3,
  192,
  156,
  1056,
  377,
  5,
  16,
  10,
  786,
  545,
  25,
  3,
  1777],
 [20, 3, 17, 1, 57],
 [4, 2, 1433, 97, 469],
 [354, 85, 16, 28, 1239, 788, 3561, 392, 776, 1413, 1089, 669, 3562, 2288],
 [1, 140, 3563, 25, 267, 515],
 [1, 3, 4, 16, 873, 170, 1059, 313, 1090, 170, 10, 313, 306, 33, 193],
 [268, 251, 3564, 966, 2, 29, 1240, 307, 3565],
 [4, 2, 201, 3566, 3567, 3568, 324, 144, 441, 32, 967, 968, 416, 578],
 [1, 150],
 [1434, 2, 210, 159],
 [22, 1, 230, 124, 789, 90, 1406],
 [73, 62, 230, 417, 11, 10, 1, 602, 1435],
 [1, 3, 4, 221, 2289, 1436, 3569, 318],
 [130, 2290, 1778, 238, 55, 1, 89, 284],
 [1, 172],
 [1, 172, 43, 111, 3570, 12],
 [216, 620, 1437, 3571, 23, 1, 273, 252, 2291],
 [4, 2, 6, 413, 3572, 46],
 [3, 1, 147, 115, 3, 651, 9],
 [1, 117, 1779, 969],
 [4,
  2,
  147,
  3573,
  9,
  3574,
  3575,
  579,
  1780,
  3576,
  5,
  180,
  1241,
  790,
  2292,
  86],
 [729, 202, 665, 26, 621, 1781, 3577, 3578, 2293, 3579, 139, 35, 1, 346],
 [849,
  2,
  47,
  175,
  3580,
  1242,
  2294,
  83,
  319,
  501,
  609,
  519,
  133,
  3581,
  9,
  208],
 [674,
  13,
  567,
  2295,
  3582,
  1782,
  55,
  228,
  1,
  25,
  330,
  2296,
  17,
  3583,
  3584,
  1438,
  229,
  38,
  2,
  874],
 [4, 2, 446, 3585, 207, 3586],
 [436, 37, 3587, 396, 1783, 141, 16, 142, 160],
 [13, 10, 6, 875, 3588, 45, 1, 89, 132, 1784, 622, 580, 8, 1091, 29, 3589],
 [1785, 2, 6, 120],
 [4, 2, 290, 446],
 [4, 2, 128],
 [205, 35, 96, 12, 2297, 4, 2, 290, 470],
 [87, 2, 520, 2298, 418, 2299, 397, 250, 1786, 6, 12, 3590],
 [1, 2300, 179, 258, 3591, 115, 767, 3592, 613, 875, 1092, 623, 411, 3593, 17],
 [38, 8, 791, 2301, 1407, 1078, 1, 39, 2302, 3594, 730],
 [124,
  1,
  231,
  2303,
  3595,
  16,
  3596,
  242,
  67,
  3597,
  3598,
  718,
  963,
  206,
  502,
  3599,
  546,
  624,
  1419,
  20,
  876,
  2303,
  2304,
  1228,
  2305],
 [1, 662, 247, 216, 625],
 [1, 547],
 [1, 43, 190, 502, 79, 14, 731, 566, 78, 170, 385, 1243],
 [2, 39, 157, 224, 3600, 7, 55, 1, 70, 77],
 [1, 234, 1093, 133, 460, 11, 416, 9],
 [13, 116, 417, 25, 13, 1414, 345, 13, 55, 1, 662],
 [130, 36, 37, 675, 4, 2, 90, 4, 35, 136],
 [50, 7, 3601, 277, 1, 3, 96, 336, 792],
 [471, 234, 434, 772, 1787, 3602, 1244, 2, 109, 877],
 [1094, 966, 133, 294, 91, 2306],
 [88, 1, 118, 3603, 878, 731, 2307, 2308],
 [4, 2, 184, 178, 1788, 1245, 879, 1246],
 [95,
  8,
  1439,
  66,
  468,
  880,
  50,
  419,
  32,
  3604,
  14,
  238,
  33,
  187,
  362,
  1,
  3605,
  398,
  330,
  260],
 [1, 155, 70],
 [1, 3, 7, 438, 86, 8, 2309, 1, 3, 81],
 [106,
  193,
  458,
  2310,
  357,
  62,
  168,
  793,
  28,
  111,
  264,
  265,
  13,
  84,
  286,
  37,
  970,
  1,
  78,
  676,
  3606],
 [38, 13, 179, 1440, 2311, 2, 179, 1789, 3607, 179],
 [1218, 1, 207, 579, 84],
 [1, 12, 72, 1790, 417, 971],
 [1, 118, 130],
 [1, 16, 308, 464],
 [1791, 195, 341, 99, 143, 192, 235, 1, 17, 472, 1792],
 [732, 1, 6, 153, 216, 3608, 3609, 1095, 473, 3610],
 [1, 120, 175, 258, 16, 1412, 3611, 197, 3612, 3613],
 [1, 666, 21, 1441, 244, 1442, 17, 2312, 3614, 3615, 3616, 3617, 247],
 [1, 503],
 [2, 292, 504, 2313],
 [1, 7, 72, 91, 3618, 79, 11, 955, 420],
 [363,
  237,
  1,
  47,
  44,
  313,
  505,
  240,
  1793,
  14,
  495,
  48,
  3,
  1794,
  3619,
  67,
  1096,
  333,
  3620,
  52,
  1097,
  581,
  2314,
  303],
 [1,
  51,
  116,
  1443,
  1067,
  794,
  3621,
  795,
  473,
  677,
  3622,
  678,
  75,
  127,
  733,
  3623,
  3624,
  8,
  337,
  1072,
  8,
  61],
 [1, 1444, 253],
 [1445, 1795, 1796, 42, 3625],
 [1098, 265, 106, 1247, 3626, 1068, 1, 153],
 [1,
  463,
  972,
  94,
  3627,
  1248,
  3628,
  1,
  56,
  156,
  92,
  3629,
  973,
  3630,
  2315,
  3631],
 [1, 198, 47, 2316],
 [3632, 129, 1797, 537, 1, 521, 1797, 279, 371, 238, 3633, 55],
 [2, 325, 323, 309, 32, 3634, 796, 3635],
 [1, 102, 260, 1, 3],
 [11,
  171,
  4,
  2,
  20,
  5,
  124,
  11,
  171,
  66,
  4,
  89,
  1716,
  797,
  214,
  15,
  24,
  514,
  196],
 [1,
  326,
  1798,
  2317,
  474,
  321,
  491,
  5,
  974,
  652,
  77,
  1446,
  217,
  652,
  2318,
  23,
  975,
  3636,
  1249,
  3637],
 [7, 1, 3, 9, 8, 159],
 [130,
  15,
  1,
  3,
  3638,
  3639,
  472,
  282,
  372,
  1799,
  516,
  335,
  1099,
  114,
  11,
  2319,
  260,
  176,
  59,
  734],
 [1, 54, 211, 143, 335, 72, 1447, 881, 735, 14, 1800, 421, 66, 192, 3640],
 [4, 159, 412, 28, 1, 93],
 [2320, 3641, 3642, 1, 179, 2321, 3643, 2322, 539, 2323, 252, 1100],
 [152, 398, 2324, 1, 140],
 [11, 1, 17, 522, 1093, 399, 1801, 143],
 [79, 1, 6, 101, 1448, 7],
 [161, 369, 882, 2325, 142, 8, 32, 2, 112, 272],
 [18, 58, 373, 261, 126, 26, 1802, 3644, 2, 2326, 305, 108, 1449],
 [1, 52, 51, 12, 255, 79],
 [1, 3, 11, 1250, 2327, 241],
 [4, 2, 29, 475, 254, 1450, 3645],
 [317, 277, 48, 3646, 3647, 3648],
 [4, 2, 300, 181, 1101, 5, 400, 381],
 [4, 2, 883, 1803, 119, 131, 2328, 351],
 [171, 660, 1, 177, 124, 3649, 2329],
 [1, 138, 44, 8],
 [4, 2330, 1, 616, 9],
 [3650, 83, 2331, 76, 501, 2331, 2, 39, 1804, 1102, 3651],
 [1, 3652, 520, 126, 495],
 [2332, 1451, 2, 338, 626, 169, 1223, 21, 92],
 [7, 1, 240, 98, 2333],
 [1, 581, 13, 503, 1103, 572],
 [1, 1452, 1773, 204, 679, 11, 266, 338, 3653, 884, 149],
 [299, 49, 2334, 533, 715, 1805, 3654, 162],
 [1, 54, 39, 138, 145, 1806, 16, 2335, 1807],
 [7, 20, 1, 680, 1808, 259],
 [1, 3655, 163, 135],
 [32, 279, 84, 2, 239, 339, 2336, 3656, 1251],
 [1, 681, 3657, 1104, 227],
 [1, 183, 1105, 798, 1453, 299, 447, 1733],
 [799,
  1106,
  156,
  129,
  736,
  3658,
  3659,
  35,
  2337,
  3660,
  2338,
  357,
  40,
  198,
  5,
  3661,
  401],
 [19, 2, 102, 28],
 [5, 2295, 2339, 2, 239, 44, 46, 1454, 2340],
 [11, 448, 393, 5, 13, 1, 98, 476, 885, 141, 2341],
 [4, 2, 223, 3662],
 [4, 2, 1455, 466, 216, 627, 241, 3663],
 [87, 2, 769],
 [305, 1, 3664, 1252, 396, 3665, 179],
 [2, 12, 477, 216, 2342, 3666, 855, 1809, 3667, 50, 3668],
 [1, 4, 39, 1456, 2343, 4, 2344],
 [1, 279, 25, 20, 11, 1457, 170],
 [1253, 1, 886, 1254, 1239, 21, 211, 144],
 [180, 1103, 1, 208, 469, 83, 209, 63, 193, 3669],
 [4, 2344, 156, 887, 2, 607, 582, 1458],
 [124, 2, 57, 36, 67, 111, 976, 4, 7, 2, 515, 26, 2345, 17],
 [1, 3, 239, 2346, 3670, 3671, 1091, 2347, 460, 1810, 628, 2348, 460, 1810],
 [1, 17, 3672, 204, 293, 42, 7, 196, 1255, 293, 34, 46],
 [1,
  52,
  541,
  2349,
  2350,
  1058,
  7,
  1,
  52,
  541,
  2349,
  2350,
  1058,
  310,
  203,
  1079],
 [189, 8, 3673, 2351, 3674, 224, 664, 99, 74, 189, 664, 888, 233, 2, 6, 201],
 [2, 1811, 21, 541, 3675, 970, 3676, 521, 30],
 [1, 63, 138, 2243, 374, 1454, 1459, 3677, 11, 781, 604, 737, 3678, 3679],
 [67, 2, 302],
 [1, 1725, 1460, 1461, 657, 1704],
 [271, 126, 2352, 3680, 677, 1107, 3681, 354, 85, 1, 1256, 487],
 [180, 311, 2, 6, 123, 800, 94, 162, 3682],
 [56, 156, 151, 48, 2, 237, 151, 205, 8, 51, 629],
 [18, 889, 889, 40, 78, 72],
 [168, 1, 153, 26],
 [90, 87, 214, 1257, 3683, 2, 121, 162, 738, 1812],
 [189, 1, 478],
 [4, 2, 6, 548, 4, 370, 378, 801, 352, 4, 1258],
 [3684, 1259, 515, 277, 1, 285],
 [15, 1, 1260, 2353, 1462, 1463, 1813],
 [2, 256, 46],
 [35, 38, 1, 6, 93],
 [1, 422],
 [977, 1252, 460, 162, 1, 1814, 3685, 291, 20, 977, 3686],
 [1, 388, 3687],
 [399, 3688, 280, 78, 3689, 2354, 2, 188, 1219, 2355, 1093, 958],
 [22, 14, 13, 116, 2220, 47, 86, 1, 3, 4, 98, 11, 978, 420, 1108, 130],
 [18, 857, 583, 79, 1, 400, 503],
 [2, 39, 3690, 1815, 347, 1261, 506, 8, 2356, 873],
 [504, 1262, 979, 3691, 1816, 493, 3692, 663, 1263, 2, 657, 1446, 2357, 3693],
 [3694, 786, 3695, 802, 3696, 2, 3697, 1109, 715, 1110],
 [423,
  628,
  1464,
  720,
  3698,
  55,
  1,
  199,
  3699,
  9,
  1465,
  3700,
  14,
  398,
  53,
  7,
  3],
 [142, 656, 1264, 2358, 2329, 3701, 1466, 803, 2, 198],
 [72, 2, 21, 391, 58, 288, 402, 44, 2359, 1817, 258, 2360, 1818, 361],
 [124, 2, 69],
 [2,
  980,
  477,
  1111,
  584,
  424,
  1251,
  1467,
  477,
  3702,
  1217,
  22,
  37,
  3703,
  3704,
  424,
  312,
  617,
  584,
  2361,
  160,
  16,
  3705,
  1112,
  3706],
 [96, 19, 1819, 3707, 2, 4, 56, 180, 3708, 460],
 [1, 188, 1468, 739, 322, 1469, 190, 194, 127, 393, 1113, 882, 3709, 64],
 [60, 11, 3710, 1, 147, 199, 3711, 423, 414, 36, 238, 1114, 507, 2362],
 [18,
  1265,
  3712,
  890,
  9,
  18,
  76,
  2,
  3,
  1815,
  891,
  138,
  74,
  1255,
  225,
  141,
  873,
  549],
 [4,
  2,
  256,
  175,
  3713,
  3714,
  3715,
  1266,
  3716,
  3717,
  1267,
  2363,
  246,
  515,
  256,
  175],
 [4, 2, 155, 2364, 630],
 [4, 981, 802, 949, 2, 117, 8, 3718, 34, 682, 63, 1820],
 [11, 3719, 2, 408],
 [1796, 85, 2, 499, 403],
 [449, 40, 479, 3720, 246, 158],
 [1821,
  1268,
  1470,
  873,
  1471,
  66,
  13,
  1,
  1115,
  580,
  740,
  3721,
  72,
  2365,
  1268],
 [2366, 128, 57, 159, 84, 1, 39, 29, 1822, 150],
 [1, 346, 8, 27, 2367, 439, 33, 361, 230],
 [1, 3, 2368, 665, 1, 425, 28, 47],
 [2, 105, 176, 3722],
 [50,
  2,
  137,
  15,
  311,
  132,
  5,
  18,
  137,
  62,
  585,
  3723,
  480,
  62,
  585,
  3724,
  1112,
  480,
  3725,
  804,
  610,
  16,
  3726,
  741],
 [261, 135, 1, 2369, 16, 343, 614],
 [508,
  2,
  982,
  283,
  18,
  2370,
  1092,
  297,
  2369,
  1823,
  3727,
  1824,
  208,
  892,
  3728,
  2371],
 [60, 1, 57, 60, 1, 201, 48],
 [2, 3, 3729, 3730, 58, 438],
 [21, 215, 576, 1825, 191, 742, 335, 30, 1826, 629, 165, 1, 3, 538, 2372],
 [1,
  52,
  631,
  412,
  46,
  13,
  423,
  771,
  2373,
  1116,
  9,
  983,
  3731,
  364,
  344,
  332,
  4,
  3732,
  9,
  237],
 [1, 138, 890, 2374],
 [2, 1433, 548, 65],
 [1, 3, 199, 658],
 [1,
  470,
  982,
  65,
  32,
  967,
  319,
  34,
  546,
  240,
  75,
  3733,
  100,
  271,
  168,
  473,
  16,
  28],
 [60, 1, 17, 50, 156, 138, 610, 1117],
 [1, 184, 156, 683, 493, 665],
 [19, 501, 130, 19, 984, 9, 113, 3734, 1472, 317, 1473, 5, 1, 478, 1473],
 [311,
  2,
  218,
  684,
  193,
  35,
  1416,
  3735,
  3736,
  1474,
  3737,
  973,
  2375,
  3738,
  3739],

In [ ]:
tok.word_index

{'feel': 1,
 'feeling': 2,
 'like': 3,
 'im': 4,
 'know': 5,
 'little': 6,
 'really': 7,
 'get': 8,
 'time': 9,
 'people': 10,
 'want': 11,
 'bit': 12,
 'think': 13,
 'even': 14,
 'would': 15,
 'one': 16,
 'way': 17,
 'ive': 18,
 'still': 19,
 'dont': 20,
 'going': 21,
 'could': 22,
 'make': 23,
 'something': 24,
 'things': 25,
 'life': 26,
 'back': 27,
 'day': 28,
 'much': 29,
 'right': 30,
 'love': 31,
 'go': 32,
 'good': 33,
 'around': 34,
 'also': 35,
 'need': 36,
 'see': 37,
 'always': 38,
 'pretty': 39,
 'feels': 40,
 'say': 41,
 'work': 42,
 'cant': 43,
 'enough': 44,
 'help': 45,
 'today': 46,
 'well': 47,
 'felt': 48,
 'feelings': 49,
 'got': 50,
 'agitated': 51,
 'less': 52,
 'someone': 53,
 'though': 54,
 'made': 55,
 'sure': 56,
 'angry': 57,
 'quite': 58,
 'makes': 59,
 'didnt': 60,
 'away': 61,
 'every': 62,
 'getting': 63,
 'person': 64,
 'happy': 65,
 'everything': 66,
 'actually': 67,
 'never': 68,
 'anxious': 69,
 'lot': 70,
 'cold': 71,
 'strange': 72,
 'find': 73,
 'thing': 74,
 'take': 75,
 'left': 76,
 'better': 77,
 'kind': 78,
 'sometimes': 79,
 'may': 80,
 'world': 81,
 'trying': 82,
 'first': 83,
 'anything': 84,
 'home': 85,
 'days': 86,
 'remember': 87,
 'started': 88,
 'afraid': 89,
 'nervous': 90,
 'without': 91,
 'come': 92,
 'scared': 93,
 'many': 94,
 'ever': 95,
 'write': 96,
 'terrified': 97,
 'tortured': 98,
 'last': 99,
 'long': 100,
 'unsure': 101,
 'weird': 102,
 'look': 103,
 'irritable': 104,
 'overwhelmed': 105,
 'read': 106,
 'able': 107,
 'shaken': 108,
 'uncertain': 109,
 'resentful': 110,
 'stop': 111,
 'rather': 112,
 'making': 113,
 'times': 114,
 'yet': 115,
 'said': 116,
 'reluctant': 117,
 'uncomfortable': 118,
 'vulnerable': 119,
 'apprehensive': 120,
 'insecure': 121,
 'selfish': 122,
 'paranoid': 123,
 'start': 124,
 'already': 125,
 'whole': 126,
 'friend': 127,
 'pissed': 128,
 'give': 129,
 'guess': 130,
 'blog': 131,
 'let': 132,
 'another': 133,
 'new': 134,
 'moment': 135,
 'excited': 136,
 'hated': 137,
 'dangerous': 138,
 'hope': 139,
 'greedy': 140,
 'part': 141,
 'friends': 142,
 'two': 143,
 'year': 144,
 'try': 145,
 'id': 146,
 'pressured': 147,
 'frustrated': 148,
 'thought': 149,
 'insulted': 150,
 'us': 151,
 'hate': 152,
 'offended': 153,
 'since': 154,
 'irritated': 155,
 'everyone': 156,
 'cranky': 157,
 'night': 158,
 'mad': 159,
 'place': 160,
 'keep': 161,
 'others': 162,
 'fucked': 163,
 'dissatisfied': 164,
 'anyone': 165,
 'annoyed': 166,
 'family': 167,
 'often': 168,
 'stressed': 169,
 'rude': 170,
 'tell': 171,
 'confused': 172,
 'bothered': 173,
 'threatened': 174,
 'week': 175,
 'god': 176,
 'hesitant': 177,
 'thinking': 178,
 'violent': 179,
 'ill': 180,
 'writing': 181,
 'distracted': 182,
 'shaky': 183,
 'jealous': 184,
 'bitchy': 185,
 'sleep': 186,
 'looking': 187,
 'wronged': 188,
 'wanted': 189,
 'talk': 190,
 'next': 191,
 'years': 192,
 'book': 193,
 'bad': 194,
 'nothing': 195,
 'hard': 196,
 'show': 197,
 'helpless': 198,
 'rushed': 199,
 'old': 200,
 'bitter': 201,
 'share': 202,
 'http': 203,
 'positive': 204,
 'might': 205,
 'house': 206,
 'free': 207,
 'almost': 208,
 'found': 209,
 'extremely': 210,
 'past': 211,
 'point': 212,
 'went': 213,
 'heart': 214,
 'post': 215,
 'put': 216,
 'use': 217,
 'slightly': 218,
 'end': 219,
 'school': 220,
 'shy': 221,
 'done': 222,
 'intimidated': 223,
 'morning': 224,
 'important': 225,
 'fearful': 226,
 'mind': 227,
 'understand': 228,
 'especially': 229,
 'body': 230,
 'frantic': 231,
 'reason': 232,
 'maybe': 233,
 'strong': 234,
 'best': 235,
 'frightened': 236,
 'least': 237,
 'perfect': 238,
 'petty': 239,
 'kids': 240,
 'face': 241,
 'thats': 242,
 'job': 243,
 'class': 244,
 'wish': 245,
 'great': 246,
 'starting': 247,
 'future': 248,
 'couldnt': 249,
 'must': 250,
 'comfortable': 251,
 'towards': 252,
 'restless': 253,
 'coming': 254,
 'sad': 255,
 'grumpy': 256,
 'far': 257,
 'probably': 258,
 'anymore': 259,
 'self': 260,
 'believe': 261,
 'lost': 262,
 'disgusted': 263,
 'close': 264,
 'eyes': 265,
 'leave': 266,
 'big': 267,
 'become': 268,
 'taking': 269,
 'mean': 270,
 'walk': 271,
 'envious': 272,
 'rebellious': 273,
 'mom': 274,
 'child': 275,
 'told': 276,
 'situation': 277,
 'girl': 278,
 'saying': 279,
 'inside': 280,
 'ask': 281,
 'care': 282,
 'lately': 283,
 'change': 284,
 'safe': 285,
 'hear': 286,
 'used': 287,
 'ok': 288,
 'call': 289,
 'particularly': 290,
 'divine': 291,
 'impatient': 292,
 'thoughts': 293,
 'room': 294,
 'completely': 295,
 'innocent': 296,
 'head': 297,
 'woke': 298,
 'hurt': 299,
 'doubtful': 300,
 'fact': 301,
 'distressed': 302,
 'tired': 303,
 'wasnt': 304,
 'truly': 305,
 'alone': 306,
 'wonderful': 307,
 'stubborn': 308,
 'decided': 309,
 'href': 310,
 'admit': 311,
 'popular': 312,
 'sit': 313,
 'creative': 314,
 'wear': 315,
 'comes': 316,
 'certain': 317,
 'man': 318,
 'run': 319,
 'sense': 320,
 'special': 321,
 'control': 322,
 'tonight': 323,
 'asked': 324,
 'brave': 325,
 'glad': 326,
 'sort': 327,
 'totally': 328,
 'cute': 329,
 'clever': 330,
 'reading': 331,
 'knowing': 332,
 'sweet': 333,
 'small': 334,
 'months': 335,
 'calm': 336,
 'wrong': 337,
 'somewhat': 338,
 'seems': 339,
 'rich': 340,
 'else': 341,
 'words': 342,
 'skeptical': 343,
 'fine': 344,
 'loved': 345,
 'inspired': 346,
 'amp': 347,
 'hostile': 348,
 'different': 349,
 'amazing': 350,
 'open': 351,
 'whatever': 352,
 'suddenly': 353,
 'came': 354,
 'enjoy': 355,
 'ways': 356,
 'woman': 357,
 'live': 358,
 'valuable': 359,
 'indecisive': 360,
 'stuff': 361,
 'guys': 362,
 'thankful': 363,
 'stupid': 364,
 'talented': 365,
 'full': 366,
 'content': 367,
 'pain': 368,
 'seeing': 369,
 'usually': 370,
 'absolutely': 371,
 'mother': 372,
 'confident': 373,
 'simply': 374,
 'super': 375,
 'lucky': 376,
 'na': 377,
 'running': 378,
 'living': 379,
 'whether': 380,
 'behind': 381,
 'somehow': 382,
 'fun': 383,
 'relaxed': 384,
 'hateful': 385,
 'honored': 386,
 'bed': 387,
 'distraught': 388,
 'successful': 389,
 'instead': 390,
 'turn': 391,
 'car': 392,
 'either': 393,
 'energy': 394,
 'wonder': 395,
 'movie': 396,
 'however': 397,
 'talking': 398,
 'longer': 399,
 'shes': 400,
 'buy': 401,
 'soon': 402,
 'wanting': 403,
 'stay': 404,
 'music': 405,
 'idea': 406,
 'wont': 407,
 'outraged': 408,
 'knew': 409,
 'trust': 410,
 'women': 411,
 'upset': 412,
 'uptight': 413,
 'doesnt': 414,
 'finally': 415,
 'spend': 416,
 'beautiful': 417,
 'real': 418,
 'together': 419,
 'hair': 420,
 'dream': 421,
 'proud': 422,
 'realized': 423,
 'red': 424,
 'respected': 425,
 'parents': 426,
 'nice': 427,
 'relationship': 428,
 'needed': 429,
 'yesterday': 430,
 'working': 431,
 'side': 432,
 'carefree': 433,
 'support': 434,
 'means': 435,
 'happened': 436,
 'lives': 437,
 'grouchy': 438,
 'putting': 439,
 'satisfied': 440,
 'ago': 441,
 'honestly': 442,
 'incredibly': 443,
 'gorgeous': 444,
 'hours': 445,
 'generous': 446,
 'miss': 447,
 'cry': 448,
 'festive': 449,
 'suspicious': 450,
 'eager': 451,
 'sitting': 452,
 'christmas': 453,
 'fabulous': 454,
 'deep': 455,
 'eating': 456,
 'seem': 457,
 'called': 458,
 'artistic': 459,
 'human': 460,
 'word': 461,
 'food': 462,
 'convinced': 463,
 'ones': 464,
 'hopeful': 465,
 'mood': 466,
 'course': 467,
 'ready': 468,
 'relieved': 469,
 'energetic': 470,
 'grateful': 471,
 'trusting': 472,
 'three': 473,
 'children': 474,
 'optimistic': 475,
 'eat': 476,
 'casual': 477,
 'assured': 478,
 'delicious': 479,
 'kept': 480,
 'type': 481,
 'lose': 482,
 'happen': 483,
 'young': 484,
 'useful': 485,
 'smart': 486,
 'experience': 487,
 'seriously': 488,
 'students': 489,
 'rest': 490,
 'needs': 491,
 'weeks': 492,
 'meet': 493,
 'wake': 494,
 'minutes': 495,
 'heard': 496,
 'watching': 497,
 'accepted': 498,
 'invigorated': 499,
 'learn': 500,
 'second': 501,
 'move': 502,
 'sincere': 503,
 'took': 504,
 'husband': 505,
 'determined': 506,
 'order': 507,
 'havent': 508,
 'blessed': 509,
 'fall': 510,
 'space': 511,
 'sarcastic': 512,
 'pleased': 513,
 'easy': 514,
 'deal': 515,
 'six': 516,
 'assaulted': 517,
 'hes': 518,
 'set': 519,
 'amused': 520,
 'giving': 521,
 'passionate': 522,
 'age': 523,
 'spent': 524,
 'etc': 525,
 'adventurous': 526,
 'using': 527,
 'gone': 528,
 'realize': 529,
 'mine': 530,
 'story': 531,
 'due': 532,
 'listen': 533,
 'mellow': 534,
 'watch': 535,
 'friendly': 536,
 'books': 537,
 'supporting': 538,
 'gets': 539,
 'joy': 540,
 'keen': 541,
 'honoured': 542,
 'began': 543,
 'listening': 544,
 'obnoxious': 545,
 'outside': 546,
 'welcomed': 547,
 'smug': 548,
 'play': 549,
 'depressed': 550,
 'please': 551,
 'waiting': 552,
 'within': 553,
 'air': 554,
 'possible': 555,
 'wants': 556,
 'theres': 557,
 'heartless': 558,
 'baby': 559,
 'wimpy': 560,
 'matter': 561,
 'given': 562,
 'worried': 563,
 'smile': 564,
 'joyful': 565,
 'fear': 566,
 'kinda': 567,
 'speak': 568,
 'high': 569,
 'cause': 570,
 'shit': 571,
 'intelligent': 572,
 'couple': 573,
 'lonely': 574,
 'party': 575,
 'training': 576,
 'half': 577,
 'money': 578,
 'hit': 579,
 'emotions': 580,
 'guy': 581,
 'moving': 582,
 'telling': 583,
 'blue': 584,
 'single': 585,
 'strongly': 586,
 'furious': 587,
 'youre': 588,
 'generally': 589,
 'ecstatic': 590,
 'worthwhile': 591,
 'hand': 592,
 'wan': 593,
 'fit': 594,
 'process': 595,
 'walked': 596,
 'continue': 597,
 'met': 598,
 'peaceful': 599,
 'mostly': 600,
 'suppose': 601,
 'vital': 602,
 'comments': 603,
 'create': 604,
 'personal': 605,
 'huge': 606,
 'timid': 607,
 'posting': 608,
 'race': 609,
 'path': 610,
 'deeply': 611,
 'son': 612,
 'whats': 613,
 'song': 614,
 'walking': 615,
 'valued': 616,
 'possibly': 617,
 'damn': 618,
 'asking': 619,
 'forward': 620,
 'stories': 621,
 'express': 622,
 'men': 623,
 'boys': 624,
 'weight': 625,
 'angered': 626,
 'game': 627,
 'constantly': 628,
 'easily': 629,
 'name': 630,
 'aggravated': 631,
 'anger': 632,
 'stand': 633,
 'privileged': 634,
 'resolved': 635,
 'precious': 636,
 'acceptable': 637,
 'door': 638,
 'decision': 639,
 'month': 640,
 'opportunity': 641,
 'beginning': 642,
 'problems': 643,
 'country': 644,
 'evening': 645,
 'moments': 646,
 'film': 647,
 'leaving': 648,
 'taken': 649,
 'sick': 650,
 'spending': 651,
 'art': 652,
 'difference': 653,
 'event': 654,
 'pressure': 655,
 'helping': 656,
 'triumphant': 657,
 'weekend': 658,
 'despite': 659,
 'whenever': 660,
 'group': 661,
 'terrific': 662,
 'trip': 663,
 'hot': 664,
 'everyday': 665,
 'virtuous': 666,
 'src': 667,
 'question': 668,
 'front': 669,
 'list': 670,
 'glamorous': 671,
 'bitch': 672,
 'desire': 673,
 'tend': 674,
 'goes': 675,
 'cool': 676,
 'four': 677,
 'middle': 678,
 'review': 679,
 'sociable': 680,
 'contented': 681,
 'dark': 682,
 'chance': 683,
 'alarmed': 684,
 'paper': 685,
 'lack': 686,
 'tomorrow': 687,
 'number': 688,
 'date': 689,
 'productive': 690,
 'win': 691,
 'add': 692,
 'learned': 693,
 'changes': 694,
 'act': 695,
 'toward': 696,
 'amount': 697,
 'lazy': 698,
 'disappointed': 699,
 'imagine': 700,
 'although': 701,
 'results': 702,
 'step': 703,
 'allow': 704,
 'career': 705,
 'news': 706,
 'weather': 707,
 'characters': 708,
 'conversation': 709,
 'choice': 710,
 'keeps': 711,
 'ended': 712,
 'sound': 713,
 'lots': 714,
 'spiteful': 715,
 'faithful': 716,
 'mental': 717,
 'light': 718,
 'girls': 719,
 'phone': 720,
 'series': 721,
 'summer': 722,
 'true': 723,
 'deserve': 724,
 'img': 725,
 'pleasant': 726,
 'reality': 727,
 'ground': 728,
 'plan': 729,
 'teacher': 730,
 'breath': 731,
 'personally': 732,
 'anxiety': 733,
 'quiet': 734,
 'upon': 735,
 'attention': 736,
 'extra': 737,
 'watched': 738,
 'managed': 739,
 'created': 740,
 'arms': 741,
 'several': 742,
 'sex': 743,
 'wearing': 744,
 'healthy': 745,
 'neurotic': 746,
 'normal': 747,
 'catch': 748,
 'emotional': 749,
 'peace': 750,
 'tears': 751,
 'hurts': 752,
 'level': 753,
 'learning': 754,
 'hold': 755,
 'attitude': 756,
 'exactly': 757,
 'pick': 758,
 'lively': 759,
 'begin': 760,
 'horrible': 761,
 'u': 762,
 'definitely': 763,
 'line': 764,
 'sorry': 765,
 'wrote': 766,
 'equally': 767,
 'physical': 768,
 'petrified': 769,
 'nature': 770,
 'worth': 771,
 'system': 772,
 'style': 773,
 'somebody': 774,
 'shut': 775,
 'gotten': 776,
 'crying': 777,
 'state': 778,
 'finding': 779,
 'yes': 780,
 'follow': 781,
 'wall': 782,
 'superior': 783,
 'isnt': 784,
 'anyway': 785,
 'says': 786,
 'eye': 787,
 'sister': 788,
 'shake': 789,
 'worry': 790,
 'questions': 791,
 'lol': 792,
 'throughout': 793,
 'main': 794,
 'saw': 795,
 'attempt': 796,
 'break': 797,
 'stomach': 798,
 'aware': 799,
 'wondering': 800,
 'late': 801,
 'usual': 802,
 'sat': 803,
 'clear': 804,
 'hungry': 805,
 'die': 806,
 'loving': 807,
 'church': 808,
 'crazy': 809,
 'guilty': 810,
 'non': 811,
 'presence': 812,
 'gave': 813,
 'products': 814,
 'forget': 815,
 'ahead': 816,
 'breathe': 817,
 'belong': 818,
 'guilt': 819,
 'reach': 820,
 'crap': 821,
 'clothes': 822,
 'example': 823,
 'involved': 824,
 'friday': 825,
 'missing': 826,
 'constant': 827,
 'negative': 828,
 'onto': 829,
 'father': 830,
 'finish': 831,
 'feet': 832,
 'worked': 833,
 'wait': 834,
 'tad': 835,
 'across': 836,
 'water': 837,
 'beloved': 838,
 'delighted': 839,
 'happens': 840,
 'thrilled': 841,
 'supposed': 842,
 'silly': 843,
 'obviously': 844,
 'reasons': 845,
 'winter': 846,
 'turning': 847,
 'sleeping': 848,
 'hadnt': 849,
 'held': 850,
 'meeting': 851,
 'approach': 852,
 'throw': 853,
 'piece': 854,
 'top': 855,
 'cos': 856,
 'talked': 857,
 'genuinely': 858,
 'issue': 859,
 'allowed': 860,
 'voice': 861,
 'finished': 862,
 'experienced': 863,
 'tree': 864,
 'dinner': 865,
 'sharing': 866,
 'tiny': 867,
 'stopped': 868,
 'arent': 869,
 'entirely': 870,
 'accept': 871,
 'experiences': 872,
 'brain': 873,
 'losing': 874,
 'problem': 875,
 'touch': 876,
 'weak': 877,
 'short': 878,
 'warm': 879,
 'offer': 880,
 'hour': 881,
 'facebook': 882,
 'bashful': 883,
 'final': 884,
 'black': 885,
 'fantastic': 886,
 'standing': 887,
 'coffee': 888,
 'bike': 889,
 'games': 890,
 'emotionally': 891,
 'complete': 892,
 'society': 893,
 'edge': 894,
 'sun': 895,
 'current': 896,
 'vicious': 897,
 'looks': 898,
 'ideas': 899,
 'inhibited': 900,
 'answer': 901,
 'direction': 902,
 'research': 903,
 'holiday': 904,
 'passed': 905,
 'breathing': 906,
 'fuck': 907,
 'letting': 908,
 'explain': 909,
 'mark': 910,
 'appalled': 911,
 'manage': 912,
 'shouldnt': 913,
 'street': 914,
 'later': 915,
 'hoping': 916,
 'theyre': 917,
 'pieces': 918,
 'reaction': 919,
 'conversations': 920,
 'lady': 921,
 'doubt': 922,
 'issues': 923,
 'currently': 924,
 'respect': 925,
 'seen': 926,
 'ability': 927,
 'focus': 928,
 'advice': 929,
 'known': 930,
 'notice': 931,
 'college': 932,
 'b': 933,
 'terribly': 934,
 'fucking': 935,
 'build': 936,
 'written': 937,
 'boyfriend': 938,
 'result': 939,
 'leg': 940,
 'early': 941,
 'expected': 942,
 'happiness': 943,
 'consider': 944,
 'hands': 945,
 'skin': 946,
 'kiss': 947,
 'except': 948,
 'lie': 949,
 'dealing': 950,
 'leaves': 951,
 'color': 952,
 'neither': 953,
 'kitchen': 954,
 'cut': 955,
 'challenge': 956,
 'improve': 957,
 'emo': 958,
 'artist': 959,
 'empty': 960,
 'considering': 961,
 'perhaps': 962,
 'fans': 963,
 'appreciative': 964,
 'certainly': 965,
 'office': 966,
 'gym': 967,
 'wouldnt': 968,
 'hey': 969,
 'smell': 970,
 'photos': 971,
 'plus': 972,
 'plot': 973,
 'study': 974,
 'lessons': 975,
 'figure': 976,
 'view': 977,
 'pull': 978,
 'headed': 979,
 'hell': 980,
 'awake': 981,
 'bouncy': 982,
 'effort': 983,
 'terrible': 984,
 'playful': 985,
 'earth': 986,
 'financial': 987,
 'happening': 988,
 'character': 989,
 'wife': 990,
 'startled': 991,
 'drop': 992,
 'truth': 993,
 'death': 994,
 'brown': 995,
 'fairly': 996,
 'spirit': 997,
 'government': 998,
 'exam': 999,
 'laugh': 1000,
 ...}

In [ ]:
tok.word_index.items()

dict_items([('feel', 1), ('feeling', 2), ('like', 3), ('im', 4), ('know', 5), ('little', 6), ('really', 7), ('get', 8), ('time', 9), ('people', 10), ('want', 11), ('bit', 12), ('think', 13), ('even', 14), ('would', 15), ('one', 16), ('way', 17), ('ive', 18), ('still', 19), ('dont', 20), ('going', 21), ('could', 22), ('make', 23), ('something', 24), ('things', 25), ('life', 26), ('back', 27), ('day', 28), ('much', 29), ('right', 30), ('love', 31), ('go', 32), ('good', 33), ('around', 34), ('also', 35), ('need', 36), ('see', 37), ('always', 38), ('pretty', 39), ('feels', 40), ('say', 41), ('work', 42), ('cant', 43), ('enough', 44), ('help', 45), ('today', 46), ('well', 47), ('felt', 48), ('feelings', 49), ('got', 50), ('agitated', 51), ('less', 52), ('someone', 53), ('though', 54), ('made', 55), ('sure', 56), ('angry', 57), ('quite', 58), ('makes', 59), ('didnt', 60), ('away', 61), ('every', 62), ('getting', 63), ('person', 64), ('happy', 65), ('everything', 66), ('actually', 67), ('never', 68), ('anxious', 69), ('lot', 70), ('cold', 71), ('strange', 72), ('find', 73), ('thing', 74), ('take', 75), ('left', 76), ('better', 77), ('kind', 78), ('sometimes', 79), ('may', 80), ('world', 81), ('trying', 82), ('first', 83), ('anything', 84), ('home', 85), ('days', 86), ('remember', 87), ('started', 88), ('afraid', 89), ('nervous', 90), ('without', 91), ('come', 92), ('scared', 93), ('many', 94), ('ever', 95), ('write', 96), ('terrified', 97), ('tortured', 98), ('last', 99), ('long', 100), ('unsure', 101), ('weird', 102), ('look', 103), ('irritable', 104), ('overwhelmed', 105), ('read', 106), ('able', 107), ('shaken', 108), ('uncertain', 109), ('resentful', 110), ('stop', 111), ('rather', 112), ('making', 113), ('times', 114), ('yet', 115), ('said', 116), ('reluctant', 117), ('uncomfortable', 118), ('vulnerable', 119), ('apprehensive', 120), ('insecure', 121), ('selfish', 122), ('paranoid', 123), ('start', 124), ('already', 125), ('whole', 126), ('friend', 127), ('pissed', 128), ('give', 129), ('guess', 130), ('blog', 131), ('let', 132), ('another', 133), ('new', 134), ('moment', 135), ('excited', 136), ('hated', 137), ('dangerous', 138), ('hope', 139), ('greedy', 140), ('part', 141), ('friends', 142), ('two', 143), ('year', 144), ('try', 145), ('id', 146), ('pressured', 147), ('frustrated', 148), ('thought', 149), ('insulted', 150), ('us', 151), ('hate', 152), ('offended', 153), ('since', 154), ('irritated', 155), ('everyone', 156), ('cranky', 157), ('night', 158), ('mad', 159), ('place', 160), ('keep', 161), ('others', 162), ('fucked', 163), ('dissatisfied', 164), ('anyone', 165), ('annoyed', 166), ('family', 167), ('often', 168), ('stressed', 169), ('rude', 170), ('tell', 171), ('confused', 172), ('bothered', 173), ('threatened', 174), ('week', 175), ('god', 176), ('hesitant', 177), ('thinking', 178), ('violent', 179), ('ill', 180), ('writing', 181), ('distracted', 182), ('shaky', 183), ('jealous', 184), ('bitchy', 185), ('sleep', 186), ('looking', 187), ('wronged', 188), ('wanted', 189), ('talk', 190), ('next', 191), ('years', 192), ('book', 193), ('bad', 194), ('nothing', 195), ('hard', 196), ('show', 197), ('helpless', 198), ('rushed', 199), ('old', 200), ('bitter', 201), ('share', 202), ('http', 203), ('positive', 204), ('might', 205), ('house', 206), ('free', 207), ('almost', 208), ('found', 209), ('extremely', 210), ('past', 211), ('point', 212), ('went', 213), ('heart', 214), ('post', 215), ('put', 216), ('use', 217), ('slightly', 218), ('end', 219), ('school', 220), ('shy', 221), ('done', 222), ('intimidated', 223), ('morning', 224), ('important', 225), ('fearful', 226), ('mind', 227), ('understand', 228), ('especially', 229), ('body', 230), ('frantic', 231), ('reason', 232), ('maybe', 233), ('strong', 234), ('best', 235), ('frightened', 236), ('least', 237), ('perfect', 238), ('petty', 239), ('kids', 240), ('face', 241), ('thats', 242), ('job', 243), ('class', 244), ('wish', 245), ('great', 246), ('starting', 247), ('future', 248), ('couldnt', 249), ('must', 250), ('comfortable', 251), ('towards', 252), ('restless', 253), ('coming', 254), ('sad', 255), ('grumpy', 256), ('far', 257), ('probably', 258), ('anymore', 259), ('self', 260), ('believe', 261), ('lost', 262), ('disgusted', 263), ('close', 264), ('eyes', 265), ('leave', 266), ('big', 267), ('become', 268), ('taking', 269), ('mean', 270), ('walk', 271), ('envious', 272), ('rebellious', 273), ('mom', 274), ('child', 275), ('told', 276), ('situation', 277), ('girl', 278), ('saying', 279), ('inside', 280), ('ask', 281), ('care', 282), ('lately', 283), ('change', 284), ('safe', 285), ('hear', 286), ('used', 287), ('ok', 288), ('call', 289), ('particularly', 290), ('divine', 291), ('impatient', 292), ('thoughts', 293), ('room', 294), ('completely', 295), ('innocent', 296), ('head', 297), ('woke', 298), ('hurt', 299), ('doubtful', 300), ('fact', 301), ('distressed', 302), ('tired', 303), ('wasnt', 304), ('truly', 305), ('alone', 306), ('wonderful', 307), ('stubborn', 308), ('decided', 309), ('href', 310), ('admit', 311), ('popular', 312), ('sit', 313), ('creative', 314), ('wear', 315), ('comes', 316), ('certain', 317), ('man', 318), ('run', 319), ('sense', 320), ('special', 321), ('control', 322), ('tonight', 323), ('asked', 324), ('brave', 325), ('glad', 326), ('sort', 327), ('totally', 328), ('cute', 329), ('clever', 330), ('reading', 331), ('knowing', 332), ('sweet', 333), ('small', 334), ('months', 335), ('calm', 336), ('wrong', 337), ('somewhat', 338), ('seems', 339), ('rich', 340), ('else', 341), ('words', 342), ('skeptical', 343), ('fine', 344), ('loved', 345), ('inspired', 346), ('amp', 347), ('hostile', 348), ('different', 349), ('amazing', 350), ('open', 351), ('whatever', 352), ('suddenly', 353), ('came', 354), ('enjoy', 355), ('ways', 356), ('woman', 357), ('live', 358), ('valuable', 359), ('indecisive', 360), ('stuff', 361), ('guys', 362), ('thankful', 363), ('stupid', 364), ('talented', 365), ('full', 366), ('content', 367), ('pain', 368), ('seeing', 369), ('usually', 370), ('absolutely', 371), ('mother', 372), ('confident', 373), ('simply', 374), ('super', 375), ('lucky', 376), ('na', 377), ('running', 378), ('living', 379), ('whether', 380), ('behind', 381), ('somehow', 382), ('fun', 383), ('relaxed', 384), ('hateful', 385), ('honored', 386), ('bed', 387), ('distraught', 388), ('successful', 389), ('instead', 390), ('turn', 391), ('car', 392), ('either', 393), ('energy', 394), ('wonder', 395), ('movie', 396), ('however', 397), ('talking', 398), ('longer', 399), ('shes', 400), ('buy', 401), ('soon', 402), ('wanting', 403), ('stay', 404), ('music', 405), ('idea', 406), ('wont', 407), ('outraged', 408), ('knew', 409), ('trust', 410), ('women', 411), ('upset', 412), ('uptight', 413), ('doesnt', 414), ('finally', 415), ('spend', 416), ('beautiful', 417), ('real', 418), ('together', 419), ('hair', 420), ('dream', 421), ('proud', 422), ('realized', 423), ('red', 424), ('respected', 425), ('parents', 426), ('nice', 427), ('relationship', 428), ('needed', 429), ('yesterday', 430), ('working', 431), ('side', 432), ('carefree', 433), ('support', 434), ('means', 435), ('happened', 436), ('lives', 437), ('grouchy', 438), ('putting', 439), ('satisfied', 440), ('ago', 441), ('honestly', 442), ('incredibly', 443), ('gorgeous', 444), ('hours', 445), ('generous', 446), ('miss', 447), ('cry', 448), ('festive', 449), ('suspicious', 450), ('eager', 451), ('sitting', 452), ('christmas', 453), ('fabulous', 454), ('deep', 455), ('eating', 456), ('seem', 457), ('called', 458), ('artistic', 459), ('human', 460), ('word', 461), ('food', 462), ('convinced', 463), ('ones', 464), ('hopeful', 465), ('mood', 466), ('course', 467), ('ready', 468), ('relieved', 469), ('energetic', 470), ('grateful', 471), ('trusting', 472), ('three', 473), ('children', 474), ('optimistic', 475), ('eat', 476), ('casual', 477), ('assured', 478), ('delicious', 479), ('kept', 480), ('type', 481), ('lose', 482), ('happen', 483), ('young', 484), ('useful', 485), ('smart', 486), ('experience', 487), ('seriously', 488), ('students', 489), ('rest', 490), ('needs', 491), ('weeks', 492), ('meet', 493), ('wake', 494), ('minutes', 495), ('heard', 496), ('watching', 497), ('accepted', 498), ('invigorated', 499), ('learn', 500), ('second', 501), ('move', 502), ('sincere', 503), ('took', 504), ('husband', 505), ('determined', 506), ('order', 507), ('havent', 508), ('blessed', 509), ('fall', 510), ('space', 511), ('sarcastic', 512), ('pleased', 513), ('easy', 514), ('deal', 515), ('six', 516), ('assaulted', 517), ('hes', 518), ('set', 519), ('amused', 520), ('giving', 521), ('passionate', 522), ('age', 523), ('spent', 524), ('etc', 525), ('adventurous', 526), ('using', 527), ('gone', 528), ('realize', 529), ('mine', 530), ('story', 531), ('due', 532), ('listen', 533), ('mellow', 534), ('watch', 535), ('friendly', 536), ('books', 537), ('supporting', 538), ('gets', 539), ('joy', 540), ('keen', 541), ('honoured', 542), ('began', 543), ('listening', 544), ('obnoxious', 545), ('outside', 546), ('welcomed', 547), ('smug', 548), ('play', 549), ('depressed', 550), ('please', 551), ('waiting', 552), ('within', 553), ('air', 554), ('possible', 555), ('wants', 556), ('theres', 557), ('heartless', 558), ('baby', 559), ('wimpy', 560), ('matter', 561), ('given', 562), ('worried', 563), ('smile', 564), ('joyful', 565), ('fear', 566), ('kinda', 567), ('speak', 568), ('high', 569), ('cause', 570), ('shit', 571), ('intelligent', 572), ('couple', 573), ('lonely', 574), ('party', 575), ('training', 576), ('half', 577), ('money', 578), ('hit', 579), ('emotions', 580), ('guy', 581), ('moving', 582), ('telling', 583), ('blue', 584), ('single', 585), ('strongly', 586), ('furious', 587), ('youre', 588), ('generally', 589), ('ecstatic', 590), ('worthwhile', 591), ('hand', 592), ('wan', 593), ('fit', 594), ('process', 595), ('walked', 596), ('continue', 597), ('met', 598), ('peaceful', 599), ('mostly', 600), ('suppose', 601), ('vital', 602), ('comments', 603), ('create', 604), ('personal', 605), ('huge', 606), ('timid', 607), ('posting', 608), ('race', 609), ('path', 610), ('deeply', 611), ('son', 612), ('whats', 613), ('song', 614), ('walking', 615), ('valued', 616), ('possibly', 617), ('damn', 618), ('asking', 619), ('forward', 620), ('stories', 621), ('express', 622), ('men', 623), ('boys', 624), ('weight', 625), ('angered', 626), ('game', 627), ('constantly', 628), ('easily', 629), ('name', 630), ('aggravated', 631), ('anger', 632), ('stand', 633), ('privileged', 634), ('resolved', 635), ('precious', 636), ('acceptable', 637), ('door', 638), ('decision', 639), ('month', 640), ('opportunity', 641), ('beginning', 642), ('problems', 643), ('country', 644), ('evening', 645), ('moments', 646), ('film', 647), ('leaving', 648), ('taken', 649), ('sick', 650), ('spending', 651), ('art', 652), ('difference', 653), ('event', 654), ('pressure', 655), ('helping', 656), ('triumphant', 657), ('weekend', 658), ('despite', 659), ('whenever', 660), ('group', 661), ('terrific', 662), ('trip', 663), ('hot', 664), ('everyday', 665), ('virtuous', 666), ('src', 667), ('question', 668), ('front', 669), ('list', 670), ('glamorous', 671), ('bitch', 672), ('desire', 673), ('tend', 674), ('goes', 675), ('cool', 676), ('four', 677), ('middle', 678), ('review', 679), ('sociable', 680), ('contented', 681), ('dark', 682), ('chance', 683), ('alarmed', 684), ('paper', 685), ('lack', 686), ('tomorrow', 687), ('number', 688), ('date', 689), ('productive', 690), ('win', 691), ('add', 692), ('learned', 693), ('changes', 694), ('act', 695), ('toward', 696), ('amount', 697), ('lazy', 698), ('disappointed', 699), ('imagine', 700), ('although', 701), ('results', 702), ('step', 703), ('allow', 704), ('career', 705), ('news', 706), ('weather', 707), ('characters', 708), ('conversation', 709), ('choice', 710), ('keeps', 711), ('ended', 712), ('sound', 713), ('lots', 714), ('spiteful', 715), ('faithful', 716), ('mental', 717), ('light', 718), ('girls', 719), ('phone', 720), ('series', 721), ('summer', 722), ('true', 723), ('deserve', 724), ('img', 725), ('pleasant', 726), ('reality', 727), ('ground', 728), ('plan', 729), ('teacher', 730), ('breath', 731), ('personally', 732), ('anxiety', 733), ('quiet', 734), ('upon', 735), ('attention', 736), ('extra', 737), ('watched', 738), ('managed', 739), ('created', 740), ('arms', 741), ('several', 742), ('sex', 743), ('wearing', 744), ('healthy', 745), ('neurotic', 746), ('normal', 747), ('catch', 748), ('emotional', 749), ('peace', 750), ('tears', 751), ('hurts', 752), ('level', 753), ('learning', 754), ('hold', 755), ('attitude', 756), ('exactly', 757), ('pick', 758), ('lively', 759), ('begin', 760), ('horrible', 761), ('u', 762), ('definitely', 763), ('line', 764), ('sorry', 765), ('wrote', 766), ('equally', 767), ('physical', 768), ('petrified', 769), ('nature', 770), ('worth', 771), ('system', 772), ('style', 773), ('somebody', 774), ('shut', 775), ('gotten', 776), ('crying', 777), ('state', 778), ('finding', 779), ('yes', 780), ('follow', 781), ('wall', 782), ('superior', 783), ('isnt', 784), ('anyway', 785), ('says', 786), ('eye', 787), ('sister', 788), ('shake', 789), ('worry', 790), ('questions', 791), ('lol', 792), ('throughout', 793), ('main', 794), ('saw', 795), ('attempt', 796), ('break', 797), ('stomach', 798), ('aware', 799), ('wondering', 800), ('late', 801), ('usual', 802), ('sat', 803), ('clear', 804), ('hungry', 805), ('die', 806), ('loving', 807), ('church', 808), ('crazy', 809), ('guilty', 810), ('non', 811), ('presence', 812), ('gave', 813), ('products', 814), ('forget', 815), ('ahead', 816), ('breathe', 817), ('belong', 818), ('guilt', 819), ('reach', 820), ('crap', 821), ('clothes', 822), ('example', 823), ('involved', 824), ('friday', 825), ('missing', 826), ('constant', 827), ('negative', 828), ('onto', 829), ('father', 830), ('finish', 831), ('feet', 832), ('worked', 833), ('wait', 834), ('tad', 835), ('across', 836), ('water', 837), ('beloved', 838), ('delighted', 839), ('happens', 840), ('thrilled', 841), ('supposed', 842), ('silly', 843), ('obviously', 844), ('reasons', 845), ('winter', 846), ('turning', 847), ('sleeping', 848), ('hadnt', 849), ('held', 850), ('meeting', 851), ('approach', 852), ('throw', 853), ('piece', 854), ('top', 855), ('cos', 856), ('talked', 857), ('genuinely', 858), ('issue', 859), ('allowed', 860), ('voice', 861), ('finished', 862), ('experienced', 863), ('tree', 864), ('dinner', 865), ('sharing', 866), ('tiny', 867), ('stopped', 868), ('arent', 869), ('entirely', 870), ('accept', 871), ('experiences', 872), ('brain', 873), ('losing', 874), ('problem', 875), ('touch', 876), ('weak', 877), ('short', 878), ('warm', 879), ('offer', 880), ('hour', 881), ('facebook', 882), ('bashful', 883), ('final', 884), ('black', 885), ('fantastic', 886), ('standing', 887), ('coffee', 888), ('bike', 889), ('games', 890), ('emotionally', 891), ('complete', 892), ('society', 893), ('edge', 894), ('sun', 895), ('current', 896), ('vicious', 897), ('looks', 898), ('ideas', 899), ('inhibited', 900), ('answer', 901), ('direction', 902), ('research', 903), ('holiday', 904), ('passed', 905), ('breathing', 906), ('fuck', 907), ('letting', 908), ('explain', 909), ('mark', 910), ('appalled', 911), ('manage', 912), ('shouldnt', 913), ('street', 914), ('later', 915), ('hoping', 916), ('theyre', 917), ('pieces', 918), ('reaction', 919), ('conversations', 920), ('lady', 921), ('doubt', 922), ('issues', 923), ('currently', 924), ('respect', 925), ('seen', 926), ('ability', 927), ('focus', 928), ('advice', 929), ('known', 930), ('notice', 931), ('college', 932), ('b', 933), ('terribly', 934), ('fucking', 935), ('build', 936), ('written', 937), ('boyfriend', 938), ('result', 939), ('leg', 940), ('early', 941), ('expected', 942), ('happiness', 943), ('consider', 944), ('hands', 945), ('skin', 946), ('kiss', 947), ('except', 948), ('lie', 949), ('dealing', 950), ('leaves', 951), ('color', 952), ('neither', 953), ('kitchen', 954), ('cut', 955), ('challenge', 956), ('improve', 957), ('emo', 958), ('artist', 959), ('empty', 960), ('considering', 961), ('perhaps', 962), ('fans', 963), ('appreciative', 964), ('certainly', 965), ('office', 966), ('gym', 967), ('wouldnt', 968), ('hey', 969), ('smell', 970), ('photos', 971), ('plus', 972), ('plot', 973), ('study', 974), ('lessons', 975), ('figure', 976), ('view', 977), ('pull', 978), ('headed', 979), ('hell', 980), ('awake', 981), ('bouncy', 982), ('effort', 983), ('terrible', 984), ('playful', 985), ('earth', 986), ('financial', 987), ('happening', 988), ('character', 989), ('wife', 990), ('startled', 991), ('drop', 992), ('truth', 993), ('death', 994), ('brown', 995), ('fairly', 996), ('spirit', 997), ('government', 998), ('exam', 999), ('laugh', 1000), ('pulling', 1001), ('babies', 1002), ('shop', 1003), ('projects', 1004), ('chocolate', 1005), ('title', 1006), ('fully', 1007), ('strength', 1008), ('brought', 1009), ('difficult', 1010), ('visit', 1011), ('stuck', 1012), ('slowly', 1013), ('saturday', 1014), ('bring', 1015), ('till', 1016), ('liked', 1017), ('unable', 1018), ('daily', 1019), ('tried', 1020), ('train', 1021), ('lovely', 1022), ('enraged', 1023), ('join', 1024), ('safety', 1025), ('blogging', 1026), ('boy', 1027), ('gracious', 1028), ('therefore', 1029), ('dance', 1030), ('ran', 1031), ('appreciate', 1032), ('student', 1033), ('drink', 1034), ('quickly', 1035), ('shopping', 1036), ('thank', 1037), ('rain', 1038), ('jealousy', 1039), ('universe', 1040), ('minute', 1041), ('awful', 1042), ('information', 1043), ('enjoying', 1044), ('kick', 1045), ('purpose', 1046), ('charming', 1047), ('blogs', 1048), ('audience', 1049), ('missed', 1050), ('simple', 1051), ('along', 1052), ('confidence', 1053), ('search', 1054), ('pass', 1055), ('gon', 1056), ('loss', 1057), ('quote', 1058), ('refuse', 1059), ('environment', 1060), ('works', 1061), ('fab', 1062), ('nauseous', 1063), ('taught', 1064), ('dad', 1065), ('funny', 1066), ('corner', 1067), ('hearts', 1068), ('key', 1069), ('low', 1070), ('progress', 1071), ('bus', 1072), ('member', 1073), ('throat', 1074), ('culture', 1075), ('warmth', 1076), ('remind', 1077), ('topic', 1078), ('www', 1079), ('opinions', 1080), ('beat', 1081), ('bigger', 1082), ('bottom', 1083), ('workers', 1084), ('cat', 1085), ('graceful', 1086), ('sadness', 1087), ('kill', 1088), ('entire', 1089), ('loud', 1090), ('nearly', 1091), ('keeping', 1092), ('connection', 1093), ('changed', 1094), ('particular', 1095), ('accomplished', 1096), ('poor', 1097), ('pray', 1098), ('died', 1099), ('beach', 1100), ('dreams', 1101), ('freaking', 1102), ('honest', 1103), ('scene', 1104), ('dizzy', 1105), ('concerned', 1106), ('five', 1107), ('scream', 1108), ('fingers', 1109), ('ease', 1110), ('favorite', 1111), ('block', 1112), ('online', 1113), ('knowledge', 1114), ('memories', 1115), ('wasted', 1116), ('freedom', 1117), ('straight', 1118), ('kid', 1119), ('sexual', 1120), ('performance', 1121), ('members', 1122), ('rule', 1123), ('fix', 1124), ('awkward', 1125), ('faith', 1126), ('highly', 1127), ('playing', 1128), ('sand', 1129), ('sunday', 1130), ('flying', 1131), ('handle', 1132), ('power', 1133), ('unhappy', 1134), ('violence', 1135), ('team', 1136), ('goal', 1137), ('rid', 1138), ('embarrassed', 1139), ('ass', 1140), ('picture', 1141), ('author', 1142), ('looked', 1143), ('interested', 1144), ('victim', 1145), ('remain', 1146), ('posts', 1147), ('became', 1148), ('push', 1149), ('yeah', 1150), ('slow', 1151), ('skills', 1152), ('count', 1153), ('grand', 1154), ('recipe', 1155), ('events', 1156), ('ordered', 1157), ('hide', 1158), ('confess', 1159), ('heat', 1160), ('actions', 1161), ('lead', 1162), ('recently', 1163), ('master', 1164), ('possibility', 1165), ('personality', 1166), ('bag', 1167), ('cover', 1168), ('pride', 1169), ('powerful', 1170), ('thanks', 1171), ('relationships', 1172), ('bird', 1173), ('flight', 1174), ('settled', 1175), ('terms', 1176), ('p

In [ ]:
# now creating the embedding matrix
embed_matrix=np.zeros(shape=(vocab_size,embed_dim))
for word,i in tok.word_index.items():
  embed_vector=word_vec_dict.get(word) #mapping the vector to word in our skipgram dictionary
  if embed_vector is not None:  # word is in the vocabulary learned by the w2v model
    embed_matrix[i]=embed_vector
  # if word is not found then embed_vector corressponding to that vector will stay zero.

In [ ]:
embed_vector.size

100

In [ ]:
embed_matrix[1]

array([-0.05340518,  0.1610322 ,  0.06696089,  0.27326739, -0.05781319,
       -0.43095869,  0.15834571,  0.59317303, -0.10689011, -0.15427607,
       -0.0419978 , -0.27120751, -0.06696089,  0.20525706,  0.13940112,
       -0.13165042,  0.10534748, -0.16642924, -0.04328715, -0.51980895,
        0.13803364,  0.18264754,  0.20897028, -0.14729239,  0.03468009,
        0.03073331, -0.20209962,  0.01706326, -0.27619401,  0.05129768,
        0.25870502,  0.10727558,  0.34160787, -0.14901966, -0.06451862,
        0.1343457 ,  0.2147035 , -0.11858265, -0.17199457, -0.3834832 ,
        0.04262262, -0.19251941, -0.16310519,  0.04724379,  0.08036602,
       -0.07967222, -0.09672153, -0.02063195,  0.0234614 ,  0.18842384,
        0.20743202, -0.14384754, -0.13108739, -0.13922577, -0.14541289,
        0.02114739,  0.2099811 , -0.03827918, -0.14145727,  0.2770679 ,
        0.02268207,  0.14162581, -0.12182491,  0.08067044, -0.22624192,
        0.24916406,  0.06809741,  0.17539093, -0.31052873,  0.27215865,
       -0.09311917,  0.02654554,  0.24681993, -0.11629981,  0.13357919,
        0.03286445,  0.02175636, -0.01509255, -0.15016054, -0.14834899,
       -0.18957621, -0.12414587, -0.06981348,  0.36446309, -0.08187313,
        0.06092591,  0.06826321,  0.12244068,  0.33575377,  0.02384415,
        0.36724386,  0.17008425, -0.01275343, -0.02784963,  0.31817526,
        0.17993538,  0.07908189, -0.24232203,  0.1014336 , -0.09971444])

**Preparing the Data for Embedding Layer**

In [ ]:
encd_rev[0]

[566, 10, 281, 49, 117, 190, 25]

In [ ]:
vocab_size

35000

In [ ]:
from keras.preprocessing.sequence import pad_sequences
# now padding to have a maximum length of 64
pad_rev= pad_sequences(encd_rev, maxlen=max_sen_len, padding='post')
pad_rev.shape   # note that we had 4749 data and we have padded each review to have a lenght of 64 words.

(4749, 64)

In [ ]:
pad_rev

array([[ 566,   10,  281, ...,    0,    0,    0],
       [  18,  178, 2211, ...,    0,    0,    0],
       [  31,  603,    1, ...,    0,    0,    0],
       ...,
       [ 693,  640,  151, ...,    0,    0,    0],
       [   1,    3, 7767, ...,    0,    0,    0],
       [  18,    2,  198, ...,    0,    0,    0]], dtype=int32)

In [ ]:
pad_rev[0] #that show index of word

array([566,  10, 281,  49, 117, 190,  25,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
      dtype=int32)

**Classification**

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras.initializers import Constant
from tensorflow.keras.layers import Dense, Embedding, Activation, Flatten

In [ ]:
model = keras.Sequential()
model.add(Embedding(input_dim=vocab_size,
                    output_dim=embed_dim,
                    input_length=max_sen_len,
                    embeddings_initializer=Constant(embed_matrix),
                    trainable=True))
model.add(layers.LSTM(64))
model.add(layers.BatchNormalization())
model.add(layers.Dense(3))

model.build(input_shape=(None, max_sen_len)) #means the first dimension (batch size) is not fixed — Keras sets it to None so the model can accept any batch size at runtime.
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 64, 100)        │     3,500,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 64)             │        42,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 3)              │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,542,691 (13.51 MB)

 Trainable params: 3,542,563 (13.51 MB)

 Non-trainable params: 128 (512.00 B)

In [ ]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer="adam",
    metrics=["accuracy"],
)

In [ ]:
model.fit(pad_rev, y_train, batch_size=8, epochs=10)

Epoch 1/10
594/594 ━━━━━━━━━━━━━━━━━━━━ 36s 56ms/step - accuracy: 0.3268 - loss: 1.0996
Epoch 2/10
594/594 ━━━━━━━━━━━━━━━━━━━━ 34s 58ms/step - accuracy: 0.3485 - loss: 1.0955
Epoch 3/10
594/594 ━━━━━━━━━━━━━━━━━━━━ 36s 61ms/step - accuracy: 0.3394 - loss: 1.0986
Epoch 4/10
594/594 ━━━━━━━━━━━━━━━━━━━━ 43s 63ms/step - accuracy: 0.6631 - loss: 0.7062
Epoch 5/10
594/594 ━━━━━━━━━━━━━━━━━━━━ 36s 55ms/step - accuracy: 0.8282 - loss: 0.4222
Epoch 6/10
594/594 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.9052 - loss: 0.2609
Epoch 7/10
594/594 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.9602 - loss: 0.1337
Epoch 8/10
594/594 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.7869 - loss: 0.4715
Epoch 9/10
594/594 ━━━━━━━━━━━━━━━━━━━━ 42s 57ms/step - accuracy: 0.9541 - loss: 0.1659
Epoch 10/10
594/594 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.9756 - loss: 0.1000

In [ ]:
4749/2

2374.5

**Testing**

**Preparing  Test Data for Embedding Layer**

In [ ]:
# Tokenize the words in the testing text data
word_token_test =[word_tokenize(i) for i in x_test]

In [ ]:
word_token_test[0]

['i',
 'sometimes',
 'feel',
 'shy',
 'about',
 'my',
 'musical',
 'taste',
 'because',
 'some',
 'of',
 'it',
 'wanders',
 'towards',
 'what',
 'some',
 'might',
 'call',
 'techno',
 'slander']

In [ ]:
# Remove stopwords from each sublist in word_token_test
filtered_tokens_test = [[word for word in sublist if word not in stop_words] for sublist in word_token_test]
# Display the first sublist of filtered tokens after removing stopwords
print(filtered_tokens_test[0])

['sometimes', 'feel', 'shy', 'musical', 'taste', 'wanders', 'towards', 'might', 'call', 'techno', 'slander']

In [ ]:
#tok.fit_on_texts(filtered_tokens_test)
encd_rev_test = tok.texts_to_sequences(filtered_tokens_test)

In [ ]:
encd_rev_test

[[79, 1, 221, 1632, 252, 205, 289],
 [5478,
  1181,
  212,
  555,
  1688,
  82,
  73,
  9,
  96,
  1725,
  26,
  1374,
  132,
  306,
  1790,
  2230,
  40,
  6,
  636],
 [55, 1, 3, 1662, 322, 505, 179, 1288, 14, 2353, 7627],
 [2, 210, 681, 639, 85],
 [313, 2, 589, 440, 3282, 75, 2884, 3319, 1, 318],
 [7, 6491, 100, 9, 1, 188, 299, 3082, 380, 799],
 [909, 7677, 1, 602, 389, 487, 729, 7677],
 [337, 1, 631],
 [1, 37, 38, 1165, 53, 205, 1000, 1, 263, 1847, 622, 49, 531, 938],
 [601, 2, 6, 512, 46, 904],
 [18, 2, 223, 105, 1914, 18, 1640, 36],
 [1, 1499, 2183, 293, 170],
 [1, 590, 399, 818, 220],
 [1, 163],
 [392, 1413, 240, 76, 2, 58, 119],
 [227, 23, 56, 3254, 1987, 44, 64, 2554, 3254, 1, 153],
 [1, 12, 226, 205, 2, 169, 1898, 29],
 [4, 455, 1, 4, 20, 314, 42],
 [1, 1376, 530, 2665, 838],
 [2, 520, 839],
 [4, 70, 1493, 2, 105],
 [2,
  295,
  105,
  143,
  45,
  1,
  1621,
  2619,
  214,
  1761,
  3233,
  1410,
  176,
  219,
  670,
  1107,
  25,
  471],
 [7541, 3825, 879, 3477, 294, 1628, 4929, 22, 1, 58, 71, 3017],
 [276, 142, 1, 3, 327, 390, 538, 406, 50, 2089, 787, 512, 7050],
 [4, 2, 201, 252, 176],
 [60, 1, 93],
 [152, 49, 2058],
 [533, 1, 164],
 [79, 1, 3, 459],
 [13, 27, 1, 3, 18, 651, 70, 9, 378, 34, 101, 4, 21, 4],
 [1,
  3,
  268,
  5771,
  637,
  704,
  6991,
  2387,
  2566,
  1072,
  91,
  1689,
  1716,
  3425,
  53,
  633],
 [4, 56, 1, 115, 1474, 78, 182, 309, 7098, 129, 219, 175, 4225, 151],
 [76,
  2,
  58,
  164,
  126,
  74,
  2149,
  6627,
  3367,
  149,
  1322,
  1946,
  2300,
  205,
  3208,
  7645,
  525],
 [496, 2150, 144, 999, 702, 566, 205, 16, 4264],
 [55, 2046, 4612, 1163, 38, 1, 386, 324, 23, 258, 605, 854, 6434, 165, 95],
 [6793, 331, 2, 108, 3091, 592],
 [1, 2139, 440, 106, 96, 35],
 [382, 1, 119, 91],
 [87, 2, 296, 1143, 28],
 [7, 1, 173, 1373, 859, 40, 3, 7637, 573, 2393, 782],
 [1,
  163,
  9,
  107,
  2043,
  84,
  347,
  2,
  733,
  9,
  66,
  59,
  169,
  2962,
  347,
  43,
  1132,
  1493],
 [60, 14, 9, 1, 184, 1241, 1203, 181, 310, 203],
 [13,
  794,
  2977,
  521,
  14,
  5574,
  7475,
  24,
  549,
  35,
  1342,
  8,
  1140,
  455,
  219,
  2511,
  2,
  177,
  760],
 [228, 2, 69],
 [43, 45, 1, 343, 126, 74],
 [2206, 1, 25, 173],
 [88, 1, 344, 186, 968, 92],
 [1, 1127, 223, 8, 4561, 43, 3233, 342, 14, 1285],
 [1, 586, 522, 1398, 55, 214, 3852],
 [1, 3, 10, 13, 4, 122, 59, 320],
 [130, 4, 2, 6, 273],
 [1, 6, 52, 226],
 [36, 502, 211, 4913, 233, 14, 1, 57],
 [1, 140],
 [1, 153, 142, 229, 1439, 142, 382, 2914, 1439, 115],
 [1, 179, 4, 685, 4039],
 [63, 582, 20, 1, 51],
 [5, 276, 1, 223, 486],
 [1, 260, 1421],
 [1, 3, 970, 39, 217],
 [404, 981, 126, 158, 2, 470, 361],
 [146, 258, 32, 1396, 139, 689, 373, 278, 40, 344, 91, 1666],
 [1, 72],
 [245, 22, 45, 75, 368, 4671, 1731, 250, 2, 296, 474, 3360, 220, 285],
 [4,
  65,
  1481,
  4,
  2,
  239,
  86,
  600,
  5134,
  283,
  1432,
  4390,
  357,
  1585,
  7024,
  468,
  67],
 [3, 582, 100, 1162, 9, 2, 199],
 [13, 2, 4286, 71, 7713, 99, 573, 86],
 [1, 375, 381, 2075, 26, 36, 106],
 [4, 2, 39, 123, 82, 1168, 3160, 4940, 763, 48, 3, 24, 913, 3, 578, 24],
 [1, 58, 148],
 [4,
  56,
  394,
  82,
  609,
  5143,
  4403,
  6190,
  649,
  233,
  149,
  2,
  288,
  1261,
  1815,
  1,
  7,
  303,
  116],
 [289,
  274,
  190,
  2021,
  720,
  2170,
  1497,
  5429,
  49,
  1193,
  861,
  276,
  116,
  1370,
  573,
  2391,
  615,
  638,
  32,
  3092,
  2578],
 [1, 567, 179, 46],
 [4, 344, 4471, 2021, 2, 6, 292],
 [1, 3, 60, 7, 282, 155, 14, 583],
 [13, 435, 644, 161, 3713, 1714, 1, 51],
 [1013, 2765, 1, 589, 65, 4],
 [31, 603, 1, 207, 215, 16],
 [73, 103, 25, 17, 515, 277, 77, 1, 51],
 [1, 57, 2845, 1013, 1565, 1065],
 [1, 3, 140, 629, 6111],
 [394, 1, 87, 2, 78, 128, 194, 4181, 66],
 [22, 1669, 27, 1, 3, 50, 140, 504, 5519, 853, 30, 1764, 189, 853, 50, 1785],
 [799, 16, 7721, 2400, 648, 2, 3269, 97, 38],
 [21,
  809,
  1037,
  176,
  3472,
  1005,
  55,
  32,
  71,
  4246,
  2528,
  2695,
  1319,
  2,
  159,
  57,
  2239],
 [1, 3, 98, 959, 190],
 [171, 25, 1, 233, 2, 7, 216, 1394, 570, 108],
 [5985, 847, 2, 69, 301, 42, 48, 429, 222],
 [298, 417, 1130, 224, 2, 253, 2179],
 [1, 263, 43, 5138, 1161, 259, 181, 215],
 [1, 3, 2648, 623, 97],
 [6491, 802, 819, 2, 122, 260, 416, 9, 84],
 [2, 120, 502, 563, 4537, 578, 1414, 1294],
 [1, 292, 79, 1, 363, 176, 813, 9, 214],
 [4, 247, 13, 80, 36, 216, 267, 1374, 638, 583, 237, 15, 3318, 2, 170],
 [37, 22, 1, 53, 117, 132, 32],
 [146, 3, 52, 89, 41, 7, 1, 52, 89, 2272],
 [5, 1, 177, 1544],
 [1, 3, 518, 433, 2928, 11],
 [76,
  2608,
  2,
  7,
  6531,
  1709,
  7426,
  35,
  327,
  367,
  301,
  1729,
  617,
  1765,
  1374,
  1545,
  2958],
 [1, 63, 51, 24, 2, 1297, 21, 87, 1058],
 [1526, 3318, 1, 84, 115, 343, 944, 4889, 276, 7363, 4917, 47, 4889, 1333],
 [1, 221, 10, 331, 181, 3183, 3231, 15, 37, 418, 26, 1061],
 [1, 450, 7452, 54, 206, 67, 519, 549, 396, 78, 92, 187, 3],
 [1, 425, 1, 3, 771, 24],
 [1, 3, 5586, 397, 239, 7, 36],
 [1, 22, 389, 1539, 6321, 134, 4817, 480, 264],
 [124, 1, 268, 155],
 [15, 1, 198, 2, 188, 148, 6938],
 [4, 2, 1417, 225, 141, 1559],
 [63, 1482, 874, 625, 63, 745, 744, 6412, 2, 886],
 [642, 13, 955, 956, 642, 1, 12, 121, 83, 2907, 99, 640],
 [8,
  218,
  879,
  2,
  254,
  72,
  320,
  3,
  2,
  8,
  30,
  2451,
  948,
  2575,
  293,
  16,
  158,
  633,
  76,
  224],
 [1,
  386,
  245,
  235,
  6432,
  1037,
  523,
  2836,
  244,
  773,
  1728,
  952,
  952,
  1720,
  167,
  7403,
  7403,
  3424,
  1720,
  1215],
 [304, 2, 290, 201, 1273, 301, 886, 28],
 [2, 90, 1474, 336, 4745],
 [305, 19, 1, 108, 2035],
 [1118, 61, 88, 1, 3059, 7118, 632, 254, 63, 51],
 [7, 149, 1017, 2, 137, 1166],
 [1, 3, 22, 776, 120, 232],
 [1, 170, 1015, 2305, 476, 462, 130, 1709],
 [43, 393, 25, 219, 82, 49, 59, 104],
 [22, 5457, 1214, 2073, 55, 1025, 322, 85, 237, 1, 285, 18, 1873],
 [208, 1, 140, 4204, 11, 29],
 [22, 1, 272, 265, 3923, 411, 160, 135],
 [4, 2, 6, 4742, 221],
 [353, 1, 70, 7767, 365, 99, 158],
 [1, 140, 2995, 3248],
 [448, 13, 810, 1716, 23, 1, 780, 18, 163, 1659, 845, 4, 765],
 [1, 105, 199],
 [1, 93],
 [597, 1600, 1786, 747, 49, 320, 917, 61, 636, 9],
 [1, 715, 252, 10, 79, 17, 103, 59, 11, 299],
 [5, 1060, 358, 564, 6118, 2191, 646, 2, 371, 911, 10],
 [1167, 103, 33, 1425, 444, 3231, 895, 7681, 2251, 981, 1670, 762],
 [916, 378, 74, 1061, 3, 7728, 2339, 621, 257, 2, 465, 46],
 [232, 395, 172, 1, 626, 41, 588, 122, 41, 588, 71],
 [235, 40, 118],
 [13, 3029, 820, 1, 450],
 [2, 443, 509, 26, 562, 10, 176, 216],
 [1, 12, 108, 54],
 [1, 174, 1763, 7650],
 [11, 905, 61, 2, 33, 1642, 5900],
 [1, 57, 318, 3085],
 [152, 2, 163, 9],
 [1, 540, 3044, 641, 2554, 602],
 [1, 147, 502, 2292, 2046],
 [1, 9, 16, 1147, 539, 5867, 312, 4782],
 [2, 273, 124, 219, 390, 642, 33, 160, 124],
 [3023, 632, 3023, 27, 19, 1328, 5000, 227, 1, 91, 53, 24, 239],
 [67, 149, 15, 1, 173, 154, 357, 524, 58, 12, 9, 419, 60, 1, 29, 84],
 [1, 98, 187, 7214, 195, 21, 948, 904, 2095],
 [4, 2, 112, 513, 323],
 [363, 243, 2, 509, 665],
 [87, 28, 720, 583, 1588, 2, 305, 65],
 [1, 223, 932, 10, 85],
 [56, 379, 351, 554, 1947, 728, 1793, 141, 2, 2017, 4283, 2155],
 [2, 78, 110, 154],
 [76, 190, 2, 90, 649, 4566, 337, 320, 277, 125, 29, 9, 1543, 21, 27],
 [1, 859, 635],
 [1, 140, 1283, 15, 11, 190, 235, 127, 205, 65],
 [1, 657, 1169, 633, 3, 7673, 569, 753, 1552, 2675, 7202, 4278],
 [1, 169],
 [2, 12, 273, 46],
 [19, 145, 1553, 14, 2, 104, 734, 9],
 [4, 2, 52, 166],
 [1, 210, 542, 6483, 847, 929, 561, 139, 45, 639],
 [1, 2045, 224],
 [2, 273, 168, 601],
 [1, 3, 4, 1056, 377, 140, 1905, 31, 29],
 [1, 155, 166, 46],
 [1, 3, 9, 165, 539, 1395, 223, 741, 1605, 20, 14, 7, 145],
 [1, 3, 278, 1421, 136, 26],
 [8, 2, 1294, 63, 163],
 [79, 1, 3, 4, 72, 81],
 [4, 2, 102],
 [116, 1, 418, 9, 1197, 487, 15, 359, 705, 5203, 154, 42, 86, 4947, 434, 1416],
 [4, 279, 955, 156, 26, 1, 225, 73, 1271, 431, 1004, 306],
 [1, 69, 135, 993, 1, 112, 3, 4039, 316],
 [5052, 1622, 1376, 1, 72, 46, 3497],
 [13, 962, 1, 1057, 3482, 179, 1089, 167, 6574, 2478],
 [266, 3380, 85, 175, 2, 565, 468, 92, 27],
 [31, 59, 1, 140],
 [2, 195, 14, 63, 51, 259],
 [48, 295, 1, 221, 236],
 [1, 117, 271],
 [1, 251, 639],
 [1, 108, 4, 552, 25, 1480],
 [208, 1, 172, 989, 442, 41, 67, 25, 21, 39, 47],
 [35, 1, 1446, 268, 572],
 [161, 378, 6994, 1857, 1957, 1, 344, 1052, 1483, 247, 299, 35, 760, 5343],
 [298,
  2,
  438,
  104,
  1,
  1175,
  28,
  6139,
  334,
  106,
  220,
  193,
  712,
  206,
  7330,
  19,
  2749],
 [1, 454],
 [11, 4, 2, 413, 216, 559, 30, 50, 3421, 50, 3421, 50, 3421, 1740, 50],
 [2, 300],
 [15, 568, 1, 572, 568, 1285, 1, 572, 2603, 1, 572],
 [2088, 29, 3160, 76, 2910, 462, 19, 3002, 3318, 191, 175, 1342, 1, 169, 93],
 [88, 2, 449, 6, 941, 144],
 [1, 221, 107, 190],
 [3, 13, 1132, 70, 1, 3, 6190, 8, 104],
 [31, 1391, 94, 10, 1, 89, 944],
 [1, 5618, 293, 145, 2830, 45, 321],
 [1, 121, 9],
 [247, 1, 90, 2844, 936, 1883],
 [1, 547],
 [1,
  291,
  535,
  2136,
  716,
  6984,
  764,
  10,
  3154,
  489,
  340,
  1097,
  1815,
  180,
  745,
  4626,
  1118,
  333,
  170,
  78],
 [11, 1, 221, 11, 383],
 [755, 829, 103, 265, 731, 1, 2235, 611, 363],
 [1, 326, 422, 22, 901, 791, 95, 222],
 [1, 1047, 10, 1, 984],
 [87, 2, 179, 263, 6782, 3156],
 [409, 189, 382, 406, 3083, 2679, 379, 1862, 35, 2, 2045, 2841, 6709, 26, 523],
 [298, 46, 2, 128],
 [1,
  12,
  89,
  1312,
  1312,
  15,
  3,
  5,
  3783,
  476,
  52,
  2904,
  957,
  6935,
  19,
  747,
  1557,
  553,
  302,
  219,
  1312,
  7,
  745,
  1312],
 [60, 1, 3, 582, 34, 25, 21, 344],
 [205, 1836, 243, 764, 2, 446],
 [1, 72, 387, 527, 6, 2534],
 [382, 1, 97, 54, 3146, 1151, 271, 160, 748, 731, 1616, 2000, 2084, 241],
 [1, 110, 38, 439, 983, 95, 2546],
 [1, 119],
 [40, 450],
 [5, 1869, 504, 143, 335, 23, 1, 305, 305, 182, 3, 289],
 [2, 112, 201, 112, 4073, 3100, 4938, 1510, 190, 794, 16],
 [87, 452, 167, 294, 497, 531, 6216, 134, 3297, 94, 192, 441, 2, 198],
 [4,
  463,
  59,
  154,
  398,
  68,
  40,
  503,
  233,
  5833,
  26,
  457,
  2033,
  95,
  212,
  125,
  40,
  3,
  4387,
  260,
  3472,
  736],
 [180, 311, 4, 185, 79, 1, 9, 675, 4, 63, 185, 1172, 213, 211, 640, 910],
 [2100, 64, 701, 21, 84, 605, 2, 69, 181],
 [1, 440, 5920, 815, 368, 48],
 [4, 2, 540, 62, 28, 444, 10, 18, 95, 598, 139, 2428, 48],
 [1, 3, 36, 6969, 1058, 829, 2148, 37, 191, 9, 1, 263, 699, 474, 1288],
 [1, 102, 4190, 3295, 719],
 [4, 19, 2, 360, 4, 2656, 3541],
 [1, 321, 4, 744, 669],
 [5, 1051, 49, 991, 991, 54, 228, 342, 2, 342, 1386, 353, 41],
 [2, 449, 46, 14, 21, 216, 864, 402, 862, 2580, 175, 914],
 [5, 73, 243, 176, 729, 4, 2, 6, 109, 66, 135],
 [11, 1, 285, 47, 233, 233, 557, 334, 683, 1, 540, 1101, 92, 723],
 [1, 3, 137, 574],
 [2,
  6,
  343,
  15,
  6107,
  9,
  277,
  3236,
  301,
  659,
  3215,
  238,
  575,
  3029,
  519,
  1178,
  4,
  698],
 [1, 72, 320, 6849, 26, 81, 4448, 1797, 158],
 [1516, 16, 573, 192, 441, 59, 1, 6, 671],
 [17, 1010],
 [1, 478, 300, 9],
 [926, 557, 24, 519, 59, 1, 326],
 [37, 1, 172, 283],
 [4, 269, 1675, 2, 459, 5213, 5428, 61, 2762, 559, 28, 3163],
 [345, 64, 213, 61, 304, 1322, 76, 820, 1877],
 [1241, 1, 3, 207, 9, 85],
 [1, 499, 71],
 [4, 2, 273, 1335, 273],
 [6390, 29, 1, 57, 660, 34, 3159, 23, 650],
 [3031,
  5131,
  864,
  306,
  1685,
  3278,
  1109,
  1,
  263,
  934,
  89,
  1109,
  566,
  208,
  1018,
  2129],
 [4530, 2450, 53, 341, 55, 1, 52, 359, 933, 1665, 304, 431, 35, 304],
 [2, 120, 21, 27],
 [83, 28, 2772, 2403, 263, 863, 1982, 970, 68, 942, 1091, 1031, 61, 467],
 [149, 33, 406, 813, 9, 2, 90, 105, 35, 813, 641, 23, 3110, 48, 7538],
 [32, 1557, 1, 3, 4, 3, 6792, 325],
 [2, 183],
 [833,
  1298,
  3869,
  927,
  7719,
  928,
  16,
  859,
  418,
  397,
  379,
  28,
  28,
  8,
  1,
  148,
  113,
  1071,
  1277,
  16,
  875],
 [4, 2, 272, 1377, 1084],
 [106,
  29,
  7435,
  2945,
  1,
  636,
  269,
  141,
  168,
  193,
  1756,
  5602,
  1,
  313,
  27,
  6068,
  734,
  9],
 [1, 3, 4, 385, 64, 79],
 [2,
  36,
  703,
  27,
  3353,
  1046,
  131,
  4397,
  454,
  26,
  2656,
  358,
  38,
  92,
  836,
  1757],
 [2792, 55, 1, 70, 77],
 [2, 3056, 547, 4229, 1626, 50, 42, 612],
 [1, 3, 5638, 7230, 108, 19, 552, 7113, 1480],
 [125, 1, 3, 4, 98],
 [192, 1, 47, 55, 606],
 [96, 135, 1, 71, 2694],
 [1, 3, 4, 72, 160, 26, 16, 75, 282, 16, 3317],
 [13, 7, 246, 1343, 1, 174, 1978, 160, 156, 37, 988],
 [92,
  27,
  473,
  719,
  1635,
  133,
  719,
  16,
  88,
  1794,
  2590,
  5831,
  185,
  7050,
  1009,
  1552,
  1762,
  1766],
 [20, 13, 1103, 70, 25, 22, 337, 161, 2, 343, 317, 25, 1784],
 [1, 3, 198, 3120, 114, 11, 319, 1158],
 [4, 2, 565, 594],
 [7, 2, 292],
 [1, 3, 22, 23, 39, 333, 366, 2821],
 [4,
  5920,
  56,
  24,
  1637,
  772,
  250,
  284,
  489,
  1,
  733,
  655,
  1506,
  1839,
  1114,
  81],
 [48, 6604],
 [1, 109, 870, 285],
 [1219, 151, 392, 1459, 160, 40, 3, 4, 285, 1524],
 [87, 452, 244, 67, 2, 451, 500, 347, 3541],
 [1, 440, 65, 1321, 46],
 [2, 148, 1194, 1200, 1200, 2512, 209, 7078, 937, 708],
 [145, 401, 15, 217, 1543, 1, 7, 1062],
 [68, 581, 62, 9, 145, 6858, 1, 263],
 [32, 186, 1, 521, 636, 9, 24, 341, 26],
 [1, 10, 93, 562],
 [1, 2314, 185, 55],
 [1, 343],
 [38, 1, 147, 8, 2039, 1050, 5967, 5852, 1642, 3274, 881],
 [1, 3, 32, 2982, 57],
 [48, 254, 84, 3541, 3786, 1662, 1218, 2, 104, 99, 2608, 84],
 [16, 264, 142, 279, 60, 3, 17, 427, 10, 20, 5],
 [790, 62, 28, 162, 52, 6, 25, 790, 59, 1, 52, 746, 1274, 52, 1412, 3964, 47],
 [125, 1, 99, 144, 534, 620, 3],
 [2, 36, 314],
 [43, 789, 4, 1739, 1, 2639, 1062, 1603, 773, 414, 47, 822, 315],
 [32, 967, 94, 114, 99, 2589, 78, 50, 287, 2, 746, 746, 2, 78, 213, 61],
 [11, 1, 346, 243],
 [1690, 6947],
 [1, 109],
 [130, 166, 5909, 40, 137, 856, 276, 400, 31, 3521],
 [5, 436, 205, 19, 1, 418, 1, 138, 729, 21, 1340, 9, 402],
 [2, 450, 2371, 955, 1279],
 [1, 1261, 51],
 [1, 14, 173, 173, 1027, 258, 14, 178],
 [38, 3002, 7673, 22, 156, 341, 1, 3, 572, 690, 389, 64],
 [19, 1, 1252, 74, 418, 108, 99],
 [19, 2, 338, 223, 130, 285, 5003, 1007, 799, 288],
 [4130, 99, 1041, 797, 1529, 257, 2, 39, 2209, 25],
 [524, 83, 573, 86, 2, 12, 253, 480, 1241, 1293, 525],
 [8, 402, 2, 2999, 242, 22, 8, 17, 626, 645],
 [60,
  942,
  29,
  18,
  863,
  3416,
  4286,
  2,
  104,
  169,
  21,
  159,
  3013,
  4024,
  2043,
  1460,
  2385,
  848,
  494,
  62,
  158],
 [83, 1, 59, 838, 963],
 [1, 97, 248],
 [180,
  23,
  2185,
  142,
  32,
  5297,
  5,
  301,
  407,
  14,
  91,
  1226,
  570,
  488,
  922,
  1287,
  1563,
  299,
  49,
  67,
  289,
  558,
  1942,
  354,
  836,
  17],
 [1, 3, 7386, 333, 1344, 15, 24, 3005, 1628],
 [1, 155, 66],
 [125, 2, 3, 52, 690],
 [1, 3, 57, 1854, 1056, 377, 806, 4249, 310, 203, 5534],
 [1, 119, 368, 514, 751],
 [1, 291, 1724],
 [3370, 401, 6629, 4, 2, 221, 241, 2924, 447],
 [1, 340, 509, 565],
 [8, 47, 1226, 1629, 23, 1, 3, 173, 25, 1361],
 [766, 40, 218, 72, 247, 96, 313, 1780, 552, 6337],
 [5920, 261, 1133, 2913, 68, 50, 16, 1, 2452],
 [1, 3, 1872, 15, 57, 242, 67, 13, 22, 68, 417, 1215],
 [105, 540, 1765, 7114, 1410, 436, 905, 83, 144],
 [50, 90, 2, 607, 221, 398, 3, 1814, 930, 126, 437],
 [22, 1, 63, 183, 2],
 [5, 2, 292, 570, 324, 668, 530, 552, 901],
 [1, 3, 344, 743, 1007, 799, 483, 532, 2557, 5, 349, 5825, 4743, 2720, 1339],
 [279, 2, 198, 271, 1973],
 [1, 78, 121, 7447, 27],
 [7,
  92,
  2855,
  154,
  582,
  41,
  422,
  17,
  521,
  925,
  1,
  397,
  36,
  1,
  159,
  169,
  352,
  115,
  19,
  978,
  419,
  1124,
  859],
 [1, 119, 115, 5260, 6562],
 [1, 102, 6847, 10, 476],
 [573, 25, 76, 23, 124, 222, 2, 548],
 [1, 3, 141, 609, 169],
 [43, 58, 261, 1, 759, 981, 224, 4455],
 [1, 3, 6627, 869, 431, 7462, 102],
 [318, 59, 1, 221, 723, 1285, 461],
 [178, 205, 468, 2, 101],
 [298, 2, 256, 303, 1134, 2342, 650, 25],
 [1, 499],
 [4, 222, 439, 827, 1, 174, 628, 3135, 303, 628, 2571, 162],
 [1, 367, 3232, 5, 96, 46, 19, 687],
 [25, 3056, 1292, 1008, 1022, 6, 1230, 4, 2, 6, 101, 24],
 [887, 264, 116, 630, 1, 170, 2665],
 [1, 210, 184, 1061],
 [508,
  776,
  115,
  19,
  6390,
  2765,
  4946,
  304,
  1007,
  389,
  154,
  3312,
  1691,
  192,
  1,
  18,
  98,
  44],
 [166, 1095, 28, 6028, 1242, 3508, 2562],
 [76, 1, 198, 84],
 [930, 77, 1781, 1, 440, 763, 24, 337],
 [145, 23, 165, 1, 118],
 [1087],
 [18, 2, 263, 1192],
 [2680, 4573, 1693, 1258, 476, 1, 234, 161, 394, 753],
 [2, 541, 8, 6326, 1862, 1608, 562, 235, 1499, 207, 207],
 [1, 98, 320, 337],
 [633, 67, 1561, 2464, 35, 5659, 2, 164],
 [76, 851, 2, 198, 2078, 4799, 842, 4940, 10, 778],
 [2682, 1731, 31, 29, 1, 509, 73, 167, 2682, 94, 349, 1774],
 [1, 3, 4, 113, 983, 43, 173, 259],
 [1, 188],
 [3, 2, 119, 4583, 2558, 600, 48, 36, 755, 419, 234, 16],
 [1, 558, 279, 54],
 [73, 1467, 1477, 130, 1, 726, 102, 1987],
 [4, 1026, 374, 4, 2, 182, 54, 4, 601, 974],
 [8, 72, 2, 14, 10, 4, 536, 4, 327, 3120, 63, 112, 1561],
 [1, 98],
 [1, 474, 3593, 17, 1, 236],
 [4, 2, 218, 223],
 [1, 3, 273, 144, 200, 7205, 7678, 6743, 4198, 997],
 [1, 105, 214, 196, 21, 2020, 505, 5967, 37, 3421],
 [2, 117, 126, 28, 46, 74, 1, 3, 1140, 728, 214, 214, 3295, 3205, 511, 195],
 [1027, 1020, 15, 288, 82, 197, 1027],
 [4, 2, 273, 36, 24, 6479, 230],
 [1, 1621, 52, 226],
 [152, 2, 4, 24, 8, 93, 208, 391, 34, 271, 61],
 [1588, 2, 58, 119, 195, 116, 195],
 [1311, 2094, 1505, 431, 661],
 [3, 4, 2, 690, 14, 54, 79, 9, 2696, 2134],
 [18, 2, 6, 231, 1163, 722, 419, 1131, 1035],
 [6406,
  1301,
  916,
  15,
  33,
  1181,
  26,
  2,
  450,
  29,
  5395,
  7524,
  14,
  79,
  233,
  567,
  70,
  450,
  214,
  297,
  614],
 [2, 58, 69],
 [2, 4751],
 [2, 375],
 [1427, 205, 1, 236, 651, 9, 76, 306],
 [2, 128],
 [1, 72, 102, 1089, 1600, 16, 78, 7193],
 [18,
  2,
  6,
  12,
  69,
  801,
  257,
  686,
  3204,
  32,
  4,
  136,
  107,
  3151,
  37,
  92,
  729,
  45],
 [1715, 540, 750, 1, 741, 98],
 [14, 1, 157],
 [67, 1, 251, 1196, 162, 3337, 1, 39, 65, 896, 1071],
 [48, 1087, 842, 1, 529, 188, 53],
 [15, 1, 108, 1593, 237, 867, 12],
 [1, 360],
 [5, 1, 153],
 [15, 1116, 9, 578, 1, 7, 147, 20, 11],
 [1, 389, 3976, 3835],
 [1, 368, 356, 98, 22, 617, 228],
 [409, 58, 6280, 2, 371, 307, 1324, 195, 29, 988, 873],
 [3254, 2, 450],
 [892, 695, 1, 440, 2, 1035, 675, 61, 1, 1192, 810],
 [1, 3, 242, 39, 239, 74, 1469],
 [1, 3, 74, 289, 459, 7261, 7, 7523],
 [1, 148, 37, 17, 3318],
 [1, 292, 316, 317, 923],
 [5, 1890, 2, 7, 173, 116],
 [2, 715, 1009, 795, 299, 241],
 [4, 2, 611, 105, 5145, 1686],
 [5, 1, 46, 141, 463, 113, 29, 1010, 67, 6452, 7050, 63, 2083, 68, 83, 160],
 [1, 953, 292, 845],
 [146, 1, 3, 558, 672, 60, 202, 7073],
 [4, 2, 90],
 [1, 166, 4, 89, 407, 107, 568, 47, 3],
 [1, 118, 5846, 1133, 194, 1343, 18, 1163],
 [62, 9, 493, 317, 1532, 3093],
 [3803, 2287, 1, 657],
 [1, 465, 254, 144],
 [712, 113, 1, 14, 119],
 [1, 3, 281, 404, 4, 122, 16, 14, 54, 464, 113, 2095, 5, 43],
 [15, 649, 24, 40, 102, 21, 2595, 644, 269, 1203, 1963, 25, 10, 258, 944],
 [2431, 24, 579, 1, 368, 618, 5, 7645, 205, 7699, 5, 138],
 [282, 29, 688, 4475, 3288, 2556, 606, 2339, 543, 1, 140, 389],
 [4, 89, 125, 1, 218, 160, 41, 127, 173, 820, 281, 25, 21, 6374],
 [1, 319, 140, 10, 282, 2207, 26, 1551],
 [75, 103, 145, 8, 287, 2, 876, 296],
 [11, 190, 5351, 9, 720, 896, 1, 177, 1015],
 [1, 7, 386, 22, 487, 1978, 772, 280],
 [1, 133, 179, 254, 1575, 24, 63, 945, 5181],
 [13, 1644, 939, 3233, 1670, 5058, 686, 3328, 133, 64, 2, 2783, 1670],
 [2, 117, 1708, 14, 779, 3294, 3237, 361],
 [2, 438],
 [1,
  2058,
  3468,
  1038,
  26,
  15,
  6,
  12,
  2057,
  2219,
  1115,
  971,
  1137,
  42,
  6100,
  144,
  15,
  431,
  941,
  1014,
  15],
 [4,
  1103,
  41,
  141,
  40,
  98,
  54,
  141,
  772,
  1470,
  26,
  16,
  3382,
  507,
  10,
  17,
  2991,
  36],
 [205, 107, 2, 8, 27, 71, 687, 158],
 [1, 18, 2021, 791, 400, 39, 472, 141],
 [149, 407, 1909, 588, 178, 2, 239, 432],
 [1, 1142, 522, 2187, 766, 2187, 766, 2, 1570],
 [2, 256, 216],
 [1, 249, 173, 259],
 [38, 40, 591, 402, 703, 1483, 6752, 205, 81, 1, 85],
 [270,
  1814,
  142,
  100,
  9,
  25,
  134,
  30,
  40,
  3,
  95,
  11,
  2111,
  265,
  66,
  41,
  171,
  545,
  588],
 [543, 1, 89, 7581, 1038, 1443],
 [31, 17, 3295, 79, 1, 221, 280],
 [1, 3, 39, 690, 86, 701, 4951, 955, 27, 178, 802],

In [ ]:
from keras.preprocessing.sequence import pad_sequences
# now padding to have a maximum length of 64
pad_rev_test= pad_sequences(encd_rev_test, maxlen=max_sen_len, padding='post')
pad_rev_test.shape   # note that we had 10 testing data and we have padded each review to have a lenght of 64 words.

(1188, 64)

dalam LSTM semua input harus sama panjang, maka perlu padding untuk mengisi kata yang kosong dengan 0

In [ ]:
pad_rev_test

array([[  79,    1,  221, ...,    0,    0,    0],
       [5478, 1181,  212, ...,    0,    0,    0],
       [  55,    1,    3, ...,    0,    0,    0],
       ...,
       [   1, 5771,   69, ...,    0,    0,    0],
       [   1,    3,  225, ...,    0,    0,    0],
       [  43,   45,    2, ...,    0,    0,    0]], dtype=int32)

In [ ]:
test_predict=model.predict(pad_rev_test)
classe_test=np.argmax(test_predict,axis=1)

38/38 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step

In [ ]:
classe_test

array([2, 2, 0, ..., 2, 1, 2])

In [ ]:
print('\nClassification Report\n')
print(classification_report(y_test, classe_test))

Classification Report

              precision    recall  f1-score   support

           0       0.94      0.92      0.93       400
           1       0.99      0.75      0.86       400
           2       0.75      0.95      0.84       388

    accuracy                           0.87      1188
   macro avg       0.89      0.87      0.87      1188
weighted avg       0.89      0.87      0.87      1188

MODEL MACHINE LEARNING

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

In [ ]:
tfidf = TfidfVectorizer(max_features=5000)

X_train_tfidf = tfidf.fit_transform(x_train)
X_test_tfidf = tfidf.transform(x_test)

In [ ]:
# Logistic Regression
ml_model = LogisticRegression(max_iter=1000)

ml_model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
y_pred_ml = ml_model.predict(X_test_tfidf)

In [ ]:
print("Accuracy:", accuracy_score(y_test, y_pred_ml))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_ml))

Accuracy: 0.9217171717171717

Classification Report:

              precision    recall  f1-score   support

           0       0.92      0.88      0.90       400
           1       0.91      0.95      0.93       400
           2       0.93      0.94      0.93       388

    accuracy                           0.92      1188
   macro avg       0.92      0.92      0.92      1188
weighted avg       0.92      0.92      0.92      1188

In [ ]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100)

rf_model.fit(X_train_tfidf, y_train)

y_pred_rf = rf_model.predict(X_test_tfidf)

print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_rf))

Accuracy: 0.914983164983165

Classification Report:

              precision    recall  f1-score   support

           0       0.93      0.90      0.91       400
           1       0.90      0.94      0.92       400
           2       0.92      0.91      0.91       388

    accuracy                           0.91      1188
   macro avg       0.92      0.91      0.91      1188
weighted avg       0.92      0.91      0.91      1188

**PERBANDINGAN:**

In [ ]:
import pandas as pd

data = {
    "Model": ["LSTM (Deep Learning)", "Logistic Regression", "Random Forest"],
    "Accuracy": [0.87, 0.9217, 0.9150],
    "Precision (Avg)": [0.89, 0.92, 0.92],
    "Recall (Avg)": [0.87, 0.92, 0.91],
    "F1-Score (Avg)": [0.87, 0.92, 0.91]
}

df_comparison = pd.DataFrame(data)

df_comparison

,Model,Accuracy,Precision (Avg),Recall (Avg),F1-Score (Avg)
0,LSTM (Deep Learning),0.8700,0.89,0.87,0.87
1,Logistic Regression,0.9217,0.92,0.92,0.92
2,Random Forest,0.9150,0.92,0.91,0.91

Berdasarkan hasil evaluasi model, dapat dilihat bahwa Logistic Regression memiliki performa terbaik dengan accuracy sebesar 92.17%, diikuti oleh Random Forest sebesar 91.50%, dan LSTM sebesar 87%. Hal ini menunjukkan bahwa model machine learning klasik mampu memberikan hasil yang lebih optimal dibandingkan model deep learning pada dataset ini.

Model LSTM sebagai representasi deep learning menunjukkan performa yang paling rendah di antara ketiga model dengan accuracy sebesar 87%. Meskipun demikian, model ini memiliki keunggulan pada recall kelas tertentu, terutama pada kelas 2 yang mencapai 0.95. Namun, kelemahan terlihat pada recall kelas 1 yang hanya sebesar 0.75, yang mengindikasikan bahwa model kurang mampu mengenali beberapa data pada kelas tersebut. Hal ini menunjukkan bahwa model LSTM masih belum optimal dan kemungkinan mengalami underfitting atau membutuhkan tuning lebih lanjut.

Logistic Regression menunjukkan performa terbaik dengan nilai accuracy, precision, recall, dan F1-score yang seimbang di sekitar 0.92. Hal ini menandakan bahwa model mampu mengklasifikasikan setiap kelas dengan baik tanpa bias terhadap kelas tertentu. Kombinasi antara metode TF-IDF dan Logistic Regression terbukti sangat efektif dalam menangani data teks, terutama pada dataset berukuran kecil hingga menengah.

Random Forest juga menunjukkan performa yang cukup baik dengan accuracy sebesar 91.50%, meskipun sedikit lebih rendah dibandingkan Logistic Regression. Model ini mampu menangkap pola non-linear dalam data, namun dalam kasus ini tidak memberikan peningkatan signifikan dibandingkan model linear. Hal ini kemungkinan disebabkan oleh karakteristik data teks yang lebih cocok direpresentasikan dengan model linear seperti Logistic Regression.

Secara keseluruhan, dapat disimpulkan bahwa model Logistic Regression merupakan model terbaik untuk kasus klasifikasi teks pada dataset ini. Hasil ini menunjukkan bahwa metode machine learning klasik masih dapat mengungguli deep learning, terutama ketika dataset tidak terlalu besar dan fitur yang digunakan sudah cukup representatif. Sementara itu, model deep learning seperti LSTM memerlukan jumlah data yang lebih besar serta tuning yang lebih kompleks agar dapat mencapai performa optimal.